### ISSUE TITLE
Target User Segment App

### ISSUE THREAD

**Issue by arpu** [olucurious/PyFCM#1]
in the firebase console i can send a message to all users  to a app 

User Segment -> APP -> com.xxx.xxx

how can i do this with PyCM?

**Comment by olucurious** [comment]
So, the fcm server endpoint always require a recipient registration_id, however there's a way to send push notifications to multiple devices without supplying registration_ids by making the app instances subscribe to a topic, I'll work on a commit to handle this feature and describe it better

Thanks for pointing this out.
Cheers.

**Comment by arpu** [comment]
https://github.com/alexbaranov49/GcmFcmSender

uses a "global" topic, all devices are subscribed to this

**Comment by olucurious** [comment]
A new version has just been completed, you can check it out
* Added topic messaging functionality

So, you can now use "global" as a topic name since you said all devices are subscribed to that topic.
You should check it out, the README file has been updated with description of the topic functionality.

Cheers.

**Comment by jiamo** [comment]
Any new news? If the project have many apps. this `User segment` send it helpful. ` all devices are subscribed to that topic.` need a extra step in client.

**Comment by Josh179** [comment]
I try with this code:

from pyfcm import FCMNotification
push_service = FCMNotification(api_key="XXXXXXXXX")

registration_id = "XXXXXXXX"
message_title = "Message title"
message_body = "test"
result = push_service.notify_single_device(registration_id=registration_id, message_title=message_title, message_body=message_body)
print result

and this is the result, but the notification never popup in the device...

**{'multicast_ids': [xxxxxxx], 'canonical_ids': 0, 'success': 1, 'topic_message_id': None, 'results': [{u'message_id': u'xxxxxxxxx'}], 'failure': 0}**

so I need to create a topic?  how I can do that with pyfcm?
I'll appreciate any kind of help

**Comment by olucurious** [comment]
@Josh179 you should have created a new issue for that

You need to setup your client to display the message, same goes for topic, you have to subscribe your clients to a topic.
