### ISSUE TITLE
name 'xrange' not defined

### ISSUE THREAD

**Issue by peterhn** [olucurious/PyFCM#10]
Ran into another problem. It looks like a lack for python3 support.

Changed `xrange` at baseapi.py:69

to simply `range` to fix it. 

Not sure what are the implications of this, but it works :)

**Comment by olucurious** [comment]
@peterhn thanks for pointing out this glitch and all the other glitches

I fixed this in https://github.com/olucurious/PyFCM/commit/1792d3a8b894b33ce5ebefd520a329a45d311717

You can install the update with pip install git+git://github.com/olucurious/PyFCM.git

Cheers
