### ISSUE TITLE
problem proxy

### ISSUE THREAD

**Issue by ferdiardianto** [olucurious/PyFCM#100]
https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L176

response = requests.post(self.FCM_END_POINT, headers=self.request_headers(), data=payload)
if self.FCM_REQ_PROXIES:
        response = requests.post(self.FCM_END_POINT, headers=self.request_headers(), data=payload, proxies=self.FCM_REQ_PROXIES)

look here read the proxy too late.
so the error will appear first. if not using a proxy.

**Comment by olucurious** [comment]
It will be fixed in the next commit

**Comment by olucurious** [comment]
Fixed here: https://github.com/olucurious/PyFCM/commit/008005ff0e74ec447939e1a8cea0fc0a513aa35a
