### ISSUE TITLE
Data message not received but notification received

### ISSUE THREAD

**Issue by mirzadelic** [olucurious/PyFCM#102]
Hi,
does anyone have this problem or it is just me.
I receive notification, but not data messages.

```
data_message = {
	"Nick" : "Mario",
	"body" : "great match!",
	"Room" : "PortugalVSDenmark"
}
push_service.notify_multiple_devices(registration_ids=registration_ids, data_message=data_message)
```

Android receives data message, but ios doesn't.

EDIT:
i got data message but with parameter `content_available=True` in `notify_multiple_devices`:
```
push_service.notify_multiple_devices(registration_ids=registration_ids, data_message=data_message, content_available=True)
```
 Is this correct way?

**Comment by olucurious** [comment]
YES! iOS requires "content_available=True"

**Comment by tomilofano** [comment]
Hello,
If I send this to Android:

```
data_message = {
    "title" : "Mario",
    "body" : "great match!",
    "click_action" : "Some value"
}

result = push_service.notify_single_device(registration_id=registration_id, data_message=data_message, content_available=True)

```
I receive the notification and its value.

But, if I send the same to iOS, this'll never arrive...
Some way to fix it?

Thanks...
