### ISSUE TITLE
"message_type" prevents successful message delivery

### ISSUE THREAD

**Issue by jappiah54** [olucurious/PyFCM#103]
On including the key value "message_type" in the "data_message" parameter, the console reads success, but receiving device never gets the message.

changed from "message_type" to a couple of string variables, rather worked.

**Comment by olucurious** [comment]
In addition to regular FCM messages, control messages are sent, indicated by the message_type field in the JSON object. The value can be either 'ack' or 'nack', or 'control' (see formats below). 

Any FCM message with an unknown message_type can be ignored by your server.
