### ISSUE TITLE
Sending to all devices

### ISSUE THREAD

**Issue by deepakbaliga** [olucurious/PyFCM#104]
I cannot send messages to all my devices. Any specific way I can achieve this without using the devices registration IDs. The same way I do it using the firebase console.

**Comment by olucurious** [comment]
You can subsribe all your users to a topic and send notification to that topic channel

**Comment by olucurious** [comment]
I also learnt this (push_service.notify_topic_subscribers(topic_name="global", message_body=message)) works but it's still largely unverified right now, you can give it a try

**Comment by webjunkie01** [comment]
@olucurious Does not work for me. I had to subscribe each id to a topic like you first suggested.
