### ISSUE TITLE
Interpreting response for `notify_multiple_devices()`

### ISSUE THREAD

**Issue by dwarrier** [olucurious/PyFCM#107]
Hi @olucurious ,

I'm a little confused as to why the object returned by `notify_multiple_devices()` is a list and not just a dictionary. I don't think we should ever get multiple response objects. According to the [FCM doc](https://firebase.google.com/docs/cloud-messaging/server#response), this is a sample response for a multicast message:
```
{ "multicast_id": 216,
  "success": 3,
  "failure": 3,
  "canonical_ids": 1,
  "results": [
    { "message_id": "1:0408" },
    { "error": "Unavailable" },
    { "error": "InvalidRegistration" },
    { "message_id": "1:1516" },
    { "message_id": "1:2342", "registration_id": "32" },
    { "error": "NotRegistered"}
  ]
}
```
And this is an example of what I receive after using `notify_multiple_devices()`:
```
[{
    'results': [
        {'error': 'InvalidRegistration'},
        {'error': 'InvalidRegistration'},
        {'error': 'InvalidRegistration'},
        {'error': 'InvalidRegistration'},
        {'error': 'InvalidRegistration'},
        {'error': 'InvalidRegistration'},
        {'error': 'InvalidRegistration'},
        {'message_id': '0:1485319787476913%c8d9d7b3f9fd7ecd'},
        {'message_id': '0:1485319787476698%c8d9d7b3f9fd7ecd'},
        ],
    'failure': 7,
    'multicast_id': 5686648884823674295,
    'success': 2,
    'canonical_ids': 0,
    }]
```
The enclosing list seems unnecessary because we should never get back more than one of these dictionaries, right? Any comments you have to clear this up would be much appreciated (:

**Comment by olucurious** [comment]
@dwarrier the thing is that for people who have more than a thousand user registration ids, multiple requests will be made because fcm doesn't process more than a thousand registration ids at once, so the list is for holding all the responses.

**Comment by dwarrier** [comment]
Good to know! Thanks for the prompt reply.
