### ISSUE TITLE
Message resend implementation

### ISSUE THREAD

**Issue by dwarrier** [olucurious/PyFCM#108]
Hi @olucurious ,

If I'm interpreting the code correctly, in `do_request()` you check for `Retry-After` header, and if it is present you resend the entire payload. However if the payload contains multiple registration ids, shouldn't we only resend the registration ids that the message has failed for? I may be misunderstanding what a payload is. I thought that deliveries to some registration ids could fail while others succeed, even if they are in the same request group.

**Comment by olucurious** [comment]
A particular payload is a single HTTP request, if the server responds with a Retry-After header, it means the entire request should be sent again, that's from my understanding of sockets and HTTP connections, I don't think they'll process some registration ids and leave others unprocessed.

**Comment by dwarrier** [comment]
Oh I see, the `Retry-After` has to do with the actual HTTP request and is completely separate from resending the messages on an individual basis. Thank you!

By the way, do you have anything set up for donations? I really appreciate your support on this library and I'd like to contribute somehow. I would submit a PR, but you seem to have that end covered!
