### ISSUE TITLE
Send rich notifications to iOS

### ISSUE THREAD

**Issue by ftab** [olucurious/PyFCM#121]
Is there a way to use PyFCM to send rich notifications to iOS 10 devices?

**Comment by olucurious** [comment]
By rich notifications, do you mean data messages?

**Comment by ftab** [comment]
I'd like an image in my notification, like so: http://www.avanderlee.com/ios-10/rich-notifications-ios-10/

**Comment by olucurious** [comment]
Okay, I've checked the link but I'm sorry I can't work it right now cos I'm currently not doing iOS development, however I'll appreciate if you can submit a pull request for a properly tested fork.

Thanks in anticipation.

**Comment by Sibasish1992** [comment]
For rich notification we just have to send a extra key in aps. "mutable-content" to 1. And in app have to write a NotificationService Extension .Thats all

**Comment by Sibasish1992** [comment]
extra_kwargs = {
        
        "mutable_content": True

    }



thats all

**Comment by ftab** [comment]
> ```
> extra_kwargs = {
>     "mutable_content": True
> }
> ```

I wish I'd thought of that! I went through and added a separate "mutable_content" parameter to the whole lot of functions just for this before you mentioned that. Sorry, just getting acquainted with pyfcm and iOS 10 notifications. Thanks for pointing it out :) as this is the answer I was looking for, closing
