### ISSUE TITLE
There was an error authenticating the sender account

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [olucurious/PyFCM#122]
I have an exception like this when i tried to launch this code:

    from pyfcm import FCMNotification

    def send_message_to_all_users(text):
        if not text:
            raise BaseException("No Text")

        push_service = FCMNotification(api_key=settings.FCM_APIKEY)
        result = push_service.notify_topic_subscribers(topic_name="global", message_body=text, message_title='JTI Mobile')
        return result

I launch this method by making POST request from my form. I get this error:

     There was an error authenticating the sender account

I have a valid FCM_APIKEY which I got from my firebase dashboard.

**Comment by olucurious** [comment]
That's not really a library issue, check this issue https://github.com/olucurious/PyFCM/issues/87 thread to see if you can find a solution there

**Comment by SuperMasterBlasterLaser** [comment]
@olucurious Now it works. Please I think you should add this problem in description of this project.

**Comment by khanImtiyaz** [comment]
i am using server api key ,then also authentication error come

**Comment by khanImtiyaz** [comment]
raise AuthenticationError("There was an error authenticating the sender account")
pyfcm.errors.AuthenticationError: There was an error authenticating the sender account

This error comes

**Comment by khixer** [comment]
still getting this error:
raise AuthenticationError("There was an error authenticating the sender account")
pyfcm.errors.AuthenticationError: There was an error authenticating the sender account

using the web-api-key available in cloud messaging tab (firebase).
