### ISSUE TITLE
Broken since v1.2.1

### ISSUE THREAD

**Issue by ProsperousBloom** [olucurious/PyFCM#126]
Hi,

PyFCM seems to be broken for iOS only, at least on our server. Android still gets messages.
PyFCM v1.2.0 works, but anything after that fails. 

I understand there were some proxy changes in 1.2.1? Whatever it is, it ended up in no messages being delivered to iOS anymore. This is quite critical, so quick help would be very appreciated.

Thanks

**Comment by olucurious** [comment]
@ProsperousBloom can you post a typical pyfcm payload you send from your server?

**Comment by ProsperousBloom** [comment]
So this happened when using notify_single - but we ran into a problem anyways, because we have several processes sending messages to many users at the same time. I switched to using notify_multiple exclusively (even for single notifications) and that fixed it (at least using 1.2.9 - didn't test 1.2.8 anymore).

Note that the error message "FCM server is temporarily not available" is misleading. It's more likely that too many requests are sent at the same time and that google rejects them as in our case. I suggest that you replace that either with "Unknown error" along with the response text, or/and get the specific error message for that case.

Anyways, great job keeping all this up to date. We're using it quite heavily and so far it's been doing well!

**Comment by olucurious** [comment]
@ProsperousBloom I'll take note of that error message and fix it in the next update. Thanks for the feedback.

Best.

**Comment by ProsperousBloom** [comment]
Hey, sorry to open this again. 
We actually still have the problem that iOS does not receive messages using any version later than 1.2.0. I made a mistake when assessing it the last time because I did so many other changes and then didn't have the time to update here. So unfortunately it still seems broken.

Here is a reproduction of code that will be delivered to Android using 1.2.1, but NOT to iOS. It WILL work with 1.2.0.:

```
from pyfcm import FCMNotification
FCM = FCMNotification(api_key='REDACTED')

data = {
    'Key': 'Broadcast',
    'Message': 'Test Message',
    'VenueID': 26,
    'OfferID': 0
    }

tokeniOS = 'REDACTED'
tokenAndroid = 'REDACTED'

result = FCM.notify_multiple_devices(registration_ids=[ tokeniOS, tokenAndroid ], data_message=data)
```

This can be replicated from both windows and linux. Using the same code and 1.2.0 it works. What exactly has changed that causes it? Could it be some out of date iOS module? Could it be related to the fact that the dictionary contains a key called 'Key'?

**Comment by olucurious** [comment]
I'll suggest you send the iOS notifications seperately with:
extra_kwargs = {
      'content_available': True
}

**Comment by ProsperousBloom** [comment]
Ok, I see. So from 1.2.0 to 1.2.1 the default for content_available has changed:

In baseapi.py for 1.2.0 you have:
```
fcm_payload['content_available']` = True
```

In baseapi.py for 1.2.1 you changed it to:
```
if content_available and isinstance(content_available, bool):
    fcm_payload['content_available'] = content_available
```

Consequently content_available wasn't sent anymore. By adding a content_available=True to the notify_multiple_devices method it works again on iOS (as well as Android). Thank you!
I wonder if that would not be the better default, since it does not seem to affect Android messages.

**Comment by olucurious** [comment]
@ProsperousBloom making it default breaks push notification for browser clients and the iOS endpoint actually needs the content_available parameter if you're sending a data payload in the message.
