### ISSUE TITLE
Send rich notifications in iOS

### ISSUE THREAD

**Issue by pramodmauryaiiita** [olucurious/PyFCM#130]
I'm not able to send "mutable_content": True in extra kwargs as an additional keyword argument (which is required to send rich notifications to iOS).

**Comment by olucurious** [comment]
Is this what you're doing?
extra_kwargs = {
    "mutable_content": True
}

**Comment by pramodmauryaiiita** [comment]
yes, in pyFCM 
if extra_kwargs:
      fcm_payload.update(extra_kwargs)
I think it should have been inside 'notification' dict
like: fcm_payload['notification']['mutable_content'] = extra_kwargs['mutable_content']

**Comment by olucurious** [comment]
Check this commit: https://github.com/olucurious/PyFCM/commit/c9e4bad937d44a903f2b0f1af8aa6fcf2d1c7d44

**Comment by olucurious** [comment]
And upgrade your pyfcm

**Comment by pramodmauryaiiita** [comment]
got it, thanks
