### ISSUE TITLE
asyncio/aiohttp support

### ISSUE THREAD

**Issue by alexey-milogradov** [olucurious/PyFCM#132]
Hi!
I encountered situation where I'd like to send push notifications asynchronously. I'd like to use asyncio for this. 

Do you have any ideas about how can I add support for asyncio?
I found tornado support commit, but it had been removed for some reason.
Could it serve as an example for adding asyncio support?

**Comment by olucurious** [comment]
Have you tested it in your fork?

I'm sorry there's no short term plan to support asyncio right now
