### ISSUE TITLE
Should allow `badge` to be 0 in send_message()

### ISSUE THREAD

**Issue by vinta** [olucurious/PyFCM#135]
Under some circumstances, we may need to send silent push notifications which have no `title` and `body` for only setting badge number.

My proposal is to modify [baseapi.py](https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L169):

```py
if badge:
    fcm_payload['notification']['badge'] = badge

# should be change to

if badge >= 0:
    fcm_payload['notification']['badge'] = badge
```

**Comment by olucurious** [comment]
You should send a pull request to the develop branch, but if you're going to do that, make sure you do: 
`
// should be change to

if badge and badge >= 0:
    fcm_payload['notification']['badge'] = badge
`
