### ISSUE TITLE
InvalidParameters error in django log

### ISSUE THREAD

**Issue by fabianbraach** [olucurious/PyFCM#139]
I'm trying to send a notification to an iOS device with the `title-loc-key` and `title-loc-args` parameters, so i can handle the localization of the message on the device. But it don't sends the message it just says `{'success': 0, 'multicast_id': 4902622197034529368, 'results': [{'error': 'InvalidParameters'}], 'failure': 1, 'canonical_ids': 0}`.
My code on the server side to send the notifications:
```
result = push_service.notify_single_device(
            registration_id = user.fcm_id,
            title_loc_key   = key,
            title_loc_args  = args,
            sound           = "Default",
            badge           = 0,
            click_action    = click_action
        )
```

Any idea how to fix this issue? I already tried using `title-loc-*` and also just `loc-*` as suggested on the fcm documentation. But pyfcm didn't accept these parameters (of course as they are not listet in the documentation).

**Comment by olucurious** [comment]
Have you tried using cURL?

**Comment by olucurious** [comment]
@fabianbraach Okayy, I've figured out what's going on, fixed it here: https://github.com/olucurious/PyFCM/commit/45c1bc2f76eb1411b9a776486306d4119db4da5a

Just do: pip install git+https://github.com/olucurious/PyFCM.git
