### ISSUE TITLE
Revert to 1.2.9 and check for array

### ISSUE THREAD

**Issue by fabianbraach** [olucurious/PyFCM#140]
The changes you made in 1.3.0 are wrong. Sorry about that. 1.2.9 works fine. My fault was to give `body_loc_args` a string instead of an array. So I got the `InvalidParameters` error. Maybe you can add a typecheck before you send the payload to the fcm end point. That should solve the problem. Firebase automatically takes the `body_loc_key` and `body_loc_args` and changes them into `loc-key` and `loc-args`. Otherwise, it is outside of the `aps` dictionary and has no effect on the notification itself.

**Comment by olucurious** [comment]
@fabianbraach I'm really embarrassed, that's why I always try to treat every complaint and request with care

**Comment by olucurious** [comment]
So, how sure are you that "Firebase automatically takes the body_loc_key and body_loc_args and changes them into loc-key and loc-args. "?

**Comment by fabianbraach** [comment]
Well, I have this parsed payload from your pyFCM library which gets send to the fcm endpoint:
```
{  
   "notification": {  
      "body_loc_args":['Demo (@demo)'],
      "body_loc_key":"notification-follow",
      "click_action":"profile",
      "sound":"Default"
   },
   "priority":"high",
   "to":"..."
}
```
On the client side on iOS I receive the following:
```
[AnyHashable("gcm.message_id"): 0:1496262762140766%f910cc44f910cc44, AnyHashable("aps"): {
    alert =     {
        "loc-args" =         (
                        (
                "Demo (@demo)"
            )
        );
        "loc-key" = "notification-follow";
    };
    category = profile;
    sound = Default;
}]

```

As you see, there is no `body_loc_key` or `body_loc_args` but `loc-key` and `loc-args`.  This is with pyFCM 1.2.9 and giving `body_loc_args` of the `notify_single_device` method an array.
With the changes you made in pyFCM 1.3.0, the output which gets send to fcm is the following:
```
{  
   "notification":{  
      "click_action":"profile",
      "loc-args":"Demo (@demo)",
      "loc-key":"notification-follow",
      "sound":"Default"
   },
   "priority":"high",
   "to":"..."
}
```
Problem is here, it seems that fcm doesn't recognize the `loc-args` and `loc-key` parameters and pack them **outside** of the `aps` dictionary so it has no effect on the notification:
```
[  
   AnyHashable("gcm.message_id"):0:1496257581534217   %f910cc44f910cc44,
   AnyHashable("aps"):{  
      category = profile; 
    sound = Default;
   },
   AnyHashable("gcm.notification.alert"):{  
      "title-loc-key":" notification-follow",
      "title-loc-args":[  
         "Demo (@demo)"
      ]
   }
]
```

I think Firebase automatically decides which parameter he needs to send to the client, because firebase knows if it is an iOS device or an android device. It is working now as i expected is except the fact that the args aren't displayed in the notification. The received `loc-args` looks a bit weird. But I don't think this is a problem with pyFCM. But I can notify you if I solved it if it is an issue with pyFCM.

**Comment by olucurious** [comment]
Alright then, I'll revert the changes in a new commit

**Comment by olucurious** [comment]
Reverted and list type checks added, thanks a lot of pointing out a potential issue and for clarifying what is really the situation here so that the library won't be broken for so many who rely on it on production.

Thanks once again..
