### ISSUE TITLE
notify_multiple_devices return emty object, but devices still receive notification

### ISSUE THREAD

**Issue by longtranista** [olucurious/PyFCM#142]
Today I got an issue, When using function notify_multiple_devices to push to 10K users at once, The result return empty object {}, But it looks like success because it took 10 sec for sending and some devices are received notification. 
Do you guys have any idea why empty object is returned ?

**Comment by olucurious** [comment]
@longtranista I think one of the requests must've returned no response Ref: https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L233 but I'll work on making sure to stop returning at that point and just add it to the response list
