### ISSUE TITLE
InternalPackageError: to

### ISSUE THREAD

**Issue by s-a-a** [olucurious/PyFCM#143]
Hi, I received this
```
File "watcher.py", line 122, in <module>
    result = push_service.notify_multiple_devices(registration_ids=clients, data_message=data_message, extra_kwargs=extra_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyfcm/fcm.py", line 204, in notify_multiple_devices
    return self.parse_responses()
  File "/usr/local/lib/python3.5/dist-packages/pyfcm/baseapi.py", line 237, in parse_responses
    raise InternalPackageError(response.text)
pyfcm.errors.InternalPackageError: to
```

I'm not quite understand what this 'to' exeption means. Here is this piece of code:
```
clients = [...]
push_service = FCMNotification(api_key="...")
extra_kwargs = {'priority': 'high'}
if clients:
    data_message = {'Type': 'invite'}
    result = push_service.notify_multiple_devices(registration_ids=clients, data_message=data_message, extra_kwargs=extra_kwargs)
```
I know that this error probably isn't pyfcm specific, but quick google search didn't give any hints to solve this.

**Comment by olucurious** [comment]
Can you try using cURL? The error means PyFCM can't parse the response from the Google FCM API

**Comment by s-a-a** [comment]
the problem is it's not 100% reproducible, everything is ok 9 out of 10 times. Anyway, I will try catch this invalid response and report details here

**Comment by olucurious** [comment]
Alright thanks

**Comment by jer-tx** [comment]
@olucurious  Running into the same problem. _extremely_ intermittent so not really possible to reproduce consistently. Is it possible FCM can just log out the raw response when it runs into this problem?
