### ISSUE TITLE
Problem when notify_multiple_devices exceeds FCM_MAX_RECIPIENTS

### ISSUE THREAD

**Issue by Proper-Job** [olucurious/PyFCM#144]
@olucurious Thank you for providing such a solid solution for FCM. It is very cool!

I do find myself in a bit of a pickle when I use FCMNotification.notify_multiple_devices() and ``registration_ids`` length exceeds ``FCM_MAX_RECIPIENTS``.
Please see the pseudo code below which illustrates the problem.

```python
registration_ids = [...] # 2000 entries
data_message = {...}
response_list = push_service.notify_multiple_devices(
    registration_ids=registration_ids, # gets chunked
    data_message=data_message
)
for response in response_list:
    for index, result in enumerate(response['results']):
        # index lies within the index range of this chunk of registration ids 
        # and will only ever be between 0-999.
        # Hence I've lost this association between this result and registration_ids
```

In order to mitigate this problem I have to employ the following workaround:

```python
registration_ids = [...] # 2000 entries
data_message = {...}
registration_id_chunks = push_service.registration_id_chunks(registration_ids)
for chunk in registration_id_chunks:
    response = push_service.notify_multiple_devices(
        registration_ids=chunk,
        data_message=data_message
     )[0]
    for index, result in enumerate(response['results']):
        # now index refers to the correct registration_id within chunk
```

It would be nice if notify_multiple_devices() didn't return a list of responses, but a single response.
This response should be a concatenation of the chunked responses.
I believe this would be a simple enough change within [parse_responses](https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L222)

Greetings
Moritz

**Comment by Proper-Job** [comment]
@olucurious how come you closed this issue?

**Comment by olucurious** [comment]
I waited for a month to see if someone else will raise a concern about the issue, the main concern I have here is backward compatibility, it will break the library for people who use it in their CI pipeline and haven't seen this conversation and the impending changes.
It has happened before and I'm just trying to avoid a reoccurrence here.
But I really do get your point and appreciate and I really wish I can find a better way to fix it without breaking the current version.

I'm still open to your ideas how to get this done, maybe a separate branch?

**Comment by Proper-Job** [comment]
Hi @olucurious 
You are correct in saying that it would break the current deployment scenario. Does that mean however that it is not necessary?
I believe this issue is related: https://github.com/olucurious/PyFCM/issues/107
If you're unwilling to change the response of notify_multiple_devices(), I believe it would be a good idea to update the README with a best practices example illustrating this caveat.
What do you think?

**Comment by olucurious** [comment]
@Proper-Job I'll see what I can do about that

**Comment by rmaciejczyk** [comment]
I think a simple solution is always the best. So what about creating a new function like notify_multiple_devices2 (or whatever name you'd like) with the new issue handling? and then you can even mark the previous function to be deprecated. I guess this is a typical way, isn't it?

**Comment by olucurious** [comment]
@rmaciejczyk I'm also considering that option
A method that returns chunked registration ids and another method that returns a single dictionary response

**Comment by Proper-Job** [comment]
@rmaciejczyk good idea

**Comment by olucurious** [comment]
@Proper-Job  the issue has been resolved in the new release

**Comment by Proper-Job** [comment]
@olucurious thank you kindly!

**Comment by Proper-Job** [comment]
@olucurious The release is tagged a bit funny.
This commit has the 1.4 tag: https://github.com/olucurious/PyFCM/commit/39f112f4775a9f14a7904ba18ee48a0952ab66e2
But it's this commit you released on PyPi, right? https://github.com/olucurious/PyFCM/commit/bb17c5519b2d0779c1caea225a633173d7f54f99

**Comment by Proper-Job** [comment]
@olucurious I think this line missing the ``raise`` statement, isn't it? https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L242

**Comment by olucurious** [comment]
@Proper-Job my bad, fixing right away

**Comment by olucurious** [comment]
Thanks for pointing out this issues, you are awesome!

**Comment by Proper-Job** [comment]
@olucurious it's the least I could do. Thank you!
