### ISSUE TITLE
push notify to web browser

### ISSUE THREAD

**Issue by FingerLiu** [olucurious/PyFCM#146]
Can I use pyfcm to push notify to web browser?

**Comment by olucurious** [comment]
@FingerLiu absolutely YES!

**Comment by Bartvds** [comment]
@olucurious The readme still notes "PyFCM supports Android and iOS.", maybe it should note it supports Web as well?

**Comment by FingerLiu** [comment]
From my test, the support of web is partial.
No browser on iphone can receive the push.

**Comment by Bartvds** [comment]
@FingerLiu Thanks for the info. Look like at least FCM and PyFCM support it as far as they can, and we wait for browsers to catch up.
