### ISSUE TITLE
Rare delay

### ISSUE THREAD

**Issue by ProsperousBloom** [olucurious/PyFCM#148]
Hi,

we send hundreds of messages every day, and there are very rare occurrences where pyfcm seems to get stuck in sending a message. I added a timer to this command in an individual context to capture when this happens, and here is an example that happened today:

result = FCM.notify_multiple_devices(registration_ids=tokens, data_message=data, time_to_live=ttl, content_available=True)

[2017-08-07 20:57:57 DEBUG] Time elapsed: 127.3872 seconds. 

In this case we sent a message to two users only. After that it worked, so it cannot be replicated easily.

My gut feeling is that for some reason there may have been a problem with that individual request. Since you use the requests library it may be useful to add a (user defined?) time_out when you call the requests.post method. That way we could immediately resend the message if there is an issue.

Thanks

**Comment by olucurious** [comment]
@ProsperousBloom can you try another test to check if exponential backoff is being activated with the 'Retry-After' header?

**Comment by ProsperousBloom** [comment]
I can add a logging command in the below block to capture the retry-after cases - is that what you mean? Again, it might take a while till this happens again - it's rare, but when it happens its disruptive.

```
        if 'Retry-After' in response.headers and int(response.headers['Retry-After']) > 0:
            sleep_time = int(response.headers['Retry-After'])
            time.sleep(sleep_time)
            return self.do_request(payload)
```

**Comment by olucurious** [comment]
Yes, let's see if the logging command will get called

**Comment by olucurious** [comment]
It's always advisable to use PyFCM in a multithreading context because the network calls are blocking, I personally use celery tasks for dispatching notifications with PyFCM in production.

**Comment by ProsperousBloom** [comment]
Ok I've added a log command in that block, and will update when it happens again.

Currently we have several asynchronous threads and one separate FCM mule that bundles all the messages once a second. That approach is better for us, since a lot of messages that the users receive are virtually the same and this way we can bundle them and use notify_multiple_devices - which should theoretically improve performance. Of course this approach fails when the server somehow delays the response, rather than raising an exception (e.g. connection errors). Luckily so far we have not encountered this too often.

**Comment by ProsperousBloom** [comment]
yeah so it actually happened again right now. The retry-after was not triggered.

**Comment by ProsperousBloom** [comment]
I should note that the delay time seems to be consistent:

[2017-08-07 22:50:54 DEBUG] Time elapsed: 127.4380 seconds.

**Comment by ProsperousBloom** [comment]
I added timeout=5 to the requests.post - let's see if this helps at all.

**Comment by ProsperousBloom** [comment]
yeah that seems to make sure the process terminates after 5 secs. 
Is this something you could add as parameter for the next version release?

**Comment by olucurious** [comment]
@ProsperousBloom is the timeout solving the problem?

**Comment by ProsperousBloom** [comment]
it's making sure the thread is terminated if there is no answer after the timeout period. For me that fixes the issue, yes.

**Comment by olucurious** [comment]
@ProsperousBloom btw are you using Google cloud?

And the thread termination is something I'm not sure I want to implement, some people want the assurance that there messages will be delivered no matter how late because they won't even bother to take care of situations where the thread is terminated and no notification is delivered

**Comment by ProsperousBloom** [comment]
No, I'm not using google cloud.

In terms of implementing it, I don't see why this would be an issue. If you make the default as timeout=None, you just use the current implementation, and if someone provides a value for timeout, then you can supply that parameter in the request.

The [requests library](http://docs.python-requests.org/en/master/user/quickstart/) actually recommends using timeout:

> You can tell Requests to stop waiting for a response after a given number of seconds with the timeout parameter. Nearly all production code should use this parameter in nearly all requests.

**Comment by olucurious** [comment]
@ProsperousBloom the issue has been resolved in the new release

**Comment by appli-intramuros** [comment]
I think there is an issue with this feature.
In case of timeout response from firebase, the do_request() must **not** be called again. Because the first call can succeed. Consequences: duplicate notifications sent.

I think that the retry must be done only in case of request error (4XX or 5XX) but never in case of timeout.

(sorry for my bad english).
