### ISSUE TITLE
typo in base.py

### ISSUE THREAD

**Issue by Guest007** [olucurious/PyFCM#151]
response_dict['multicast_id'].append(multicast_id) but must be 'multicast_ids' as response_dict key

**Comment by olucurious** [comment]
Wow, thanks a lot for pointing that out

**Comment by olucurious** [comment]
Fixed in the new 1.4.2 release

**Comment by Guest007** [comment]
Glad to help ;-)

**Comment by arvindnrbt** [comment]
Please update the releases page. I spent almost an hour wondering what went wrong when I got an exception stating just `multicast_id`. The current stable release 1.4.0 has this problem.

**Comment by olucurious** [comment]
@arvindnrbt can you provide more details by posting the exception here?

**Comment by arvindnrbt** [comment]
The exception just says `multicast_id`. This is because of the typo in `v1.4.0`. The problem is solved in the newer versions.
