### ISSUE TITLE
New Firebase Cloud Messaging API

### ISSUE THREAD

**Issue by se-bastiaan** [olucurious/PyFCM#165]
Yesterday Google's Firebase team announce some cool new stuff at the Firebase Dev Summit:
https://firebase.googleblog.com/2017/10/whats-new-at-firebase-dev-summit-2017.html

One of these new things is the improvement to the Cloud Messaging API:
> Firebase Cloud Messaging (FCM) gives you an easy way to send notifications to your users, either programmatically or through the Firebase Console. However, sending cross-platform notifications with more complex functionality has been difficult, sometimes requiring you to create multiple, separate messages.
>
>Today, we're announcing a new RESTful, FCM HTTP v1 API that makes it safer and easier to send messages to your cross-platform applications. The new FCM API allows you to use platform-specific fields in a single notification. For example, you might send a simple text notification to iOS, but a request with a `click_action` to Android, all in one API call. To read more about the new FCM API, visit our documentation.

The HTTP and XMPP protocols we could use before are now called 'Legacy HTTP' and 'Legacy XMPP' in [the documentation](https://firebase.google.com/docs/cloud-messaging/server#choose). Since the protocols are not deprecated or scheduled for shutdown (at least not that I can find) I feel there is no real _need_ to change this library (yet).

Still, I was thinking that it would be great if PyFCM would start using this new `FCM HTTP v1 API` since it seems so much more powerful. What do you think?

**Comment by olucurious** [comment]
Will create a new branch to start working on that

**Comment by jiamo** [comment]
Hi I have write a very simple wrap using the new api. (https://github.com/jiamo/pfcm) May be you can have a look at it.

**Comment by babus** [comment]
Any progress on this? @olucurious

**Comment by ruoyush** [comment]
It seems that the new api doesn't support registration_ids parameter which are used to send notification to multiple devices. Please consider this problem when developing the new library. Thank you.

**Comment by romantolkachyov** [comment]
I think we must consider this issue #208 

It would we wrong to broke backward-compatibility for old users. If new users choices google client it would be better to remain this library as is and warn users about deprecation.

**Comment by se-bastiaan** [comment]
It's not wrong to break backwards-compatibility if you correctly communicate breaking changes and bump the version accordingly. However, since the Admin SDK includes an implementation of Cloud Messaging maintained by Google/Firebase and is also open source I do think that it would not hurt to deprecate this package due to the old version of the API being used and have Firebase's Admin SDK supersede it.

**Comment by KodiKraig** [comment]
Can anyone confirm if this package still works? I have been trying for a few days to get push notifications working for an android app with no success. I am getting responses from the FCM server in the form:

`{'multicast_ids': [8215030081897783522], 'success': 1, 'failure': 0, 'canonical_ids': 0, 'results': [{'message_id': '0:1540961905811607%796bd2c1796bd2c1'}], 'topic_message_id': None}`

To me it seems that response is a successful one but the notifications aren't going through to the device. Should I switch to the Admin SDK?

**Comment by se-bastiaan** [comment]
Yes this package still works, we use it in production. However, that is not what this issue is about so you should open a new issue to ask for help.

**Comment by romantolkachyov** [comment]
@KodiKraig check your mobile application please. This library working as expected.
