### ISSUE TITLE
Gevent support

### ISSUE THREAD

**Issue by markallenmobi** [olucurious/PyFCM#168]
The library works great, however does not seem compatible with gevent - as it blocks in this environment.

If it is not using native code via a compiled library, and is all in python, then I believe adding:

```
from gevent import monkey
monkey.patch_all()
```

to the top of each file that uses blocking sockets should get it to work with gevent.

**Comment by olucurious** [comment]
@markallenmobi it will be appreciated if you can submit a pull request for that support
