### ISSUE TITLE
pip install pyfcm fatal error

### ISSUE THREAD

**Issue by folt** [olucurious/PyFCM#170]
Hi
I'm trying to install pyfcm
`pip install pyfcm==1.4.3`
I get a fatal error

`Collecting pyfcm==1.4.3
  Using cached pyfcm-1.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j_/qkr9lhfd0g593b64465q50cr0000gn/T/pycharm-packaging/pyfcm/setup.py", line 41, in <module>
        long_description=read('README.rst'),
      File "/private/var/folders/j_/qkr9lhfd0g593b64465q50cr0000gn/T/pycharm-packaging/pyfcm/setup.py", line 17, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4157: ordinal not in range(128)
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j_/qkr9lhfd0g593b64465q50cr0000gn/T/pycharm-packaging/pyfcm/`

my version of python
`Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) `
I'm using macOS

**Comment by folt** [comment]
pyfcm==1.4.2 
Installed without problems

**Comment by olucurious** [comment]
Can you try to install from this branch: https://github.com/olucurious/PyFCM/tree/UnicodeErrorFix

Let's see if that will work in your environment

**Comment by folt** [comment]
my command 
`pip install git+https://github.com/olucurious/PyFCM/tree/UnicodeErrorFix`
I get a fatal error
`Collecting git+https://github.com/olucurious/PyFCM/tree/UnicodeErrorFix
  Cloning https://github.com/olucurious/PyFCM/tree/UnicodeErrorFix to /private/var/folders/j_/qkr9lhfd0g593b64465q50cr0000gn/T/pip-3vqrm1c3-build
remote: Not Found
fatal: repository 'https://github.com/olucurious/PyFCM/tree/UnicodeErrorFix/' not found
Command "git clone -q https://github.com/olucurious/PyFCM/tree/UnicodeErrorFix /private/var/folders/j_/qkr9lhfd0g593b64465q50cr0000gn/T/pip-3vqrm1c3-build" failed with error code 128 in None`

**Comment by olucurious** [comment]
Fixed in https://github.com/olucurious/PyFCM/pull/179
