### ISSUE TITLE
Pip install UnicodeDecodeError

### ISSUE THREAD

**Issue by mazz** [olucurious/PyFCM#174]
Installing pyfcm 1.4.3 via pip results in a UnicodeDecodeError. Reverting back to 'pyfcm==1.4.2' avoids the error:

  Traceback (most recent call last):", "      File \"<string>\", line 1, in <module>", "      File \"/tmp/pip-build-sfpfcgfi/pyfcm/setup.py\", line 41, in <module>", "        long_description=read('README.rst'),", "      File \"/tmp/pip-build-sfpfcgfi/pyfcm/setup.py\", line 17, in read", "        return open(os.path.join(os.path.dirname(__file__), fname)).read()", “
      File \"/srv/pyramid/kjvrvg/venv/lib/python3.5/encodings/ascii.py\", line 26, in decode”,
 "        return codecs.ascii_decode(input, self.errors)[0]", "    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4157: ordinal not in range(128)", "

**Comment by olucurious** [comment]
Can you try to install from this branch: https://github.com/olucurious/PyFCM/tree/UnicodeErrorFix

Let's see if that will work in your environment

**Comment by mazz** [comment]
I decided to set LC_ALL to `en_US.UTF-8` to avoid the same issue with the pyroma 2.3 pip install, which seems to have worked. So I will try fetching from 1.4.3 again and see if the problem goes away.

**Comment by mazz** [comment]
My pip requirements.txt contains:

`-e "git+https://github.com/olucurious/PyFCM.git@UnicodeErrorFix#egg=pyfcm"`

It failed:
```
Cloning https://github.com/olucurious/PyFCM.git (to UnicodeErrorFix) to /srv/pyramid/faithfulaudio.kjvrvg/venv/src/pyfcm", "    Complete output from command python setup.py egg_info:", "    Traceback (most recent call last):", "      File \"<string>\", line 1, in <module>", "      File \"/srv/pyramid/faithfulaudio.kjvrvg/venv/src/pyfcm/setup.py\", line 23, in <module>", "        exec (read('pyfcm/__meta__.py'), meta)", "      File \"/srv/pyramid/faithfulaudio.kjvrvg/venv/src/pyfcm/setup.py\", line 17, in read", "        return open(os.path.join(os.path.dirname(__file__), fname)).read().decode(\"utf8\")", "    AttributeError: 'str' object has no attribute 'decode'", "    ", "    ----------------------------------------"], "warnings": []}
```

**Comment by mazz** [comment]
-e "git+https://github.com/olucurious/PyFCM.git@UnicodeErrorFix#egg=pyfcm"

**Comment by olucurious** [comment]
Fixed in https://github.com/olucurious/PyFCM/pull/179
