### ISSUE TITLE
iOS 10 rich notifications mutable-content issue

### ISSUE THREAD

**Issue by mj3052** [olucurious/PyFCM#176]
When setting the extra_kwargs on the payload PyFCM currently does the following:

```python
if extra_kwargs:
    fcm_payload['notification'].update(extra_kwargs)
```

In order to use rich notifications the "mutable_content" flag needs to be set, but NOT inside the "notification" part of the payload as `extra_kwargs` is right now. I confirmed this by changing the code to:

```python
if extra_kwargs:
    fcm_payload.update(extra_kwargs)
```

Which made rich content work just fine. I however gathered from earlier issues that some people wanted to set extra keywords on the "notification" part of the payload in some cases, but we also need to be able to add keywords outside of it. 

We could either add "mutable_content" as a parameter on each function, or we could cleaner add the ability to both add extra keywords to both the "notification" part itself, and to the outer payload. For example by doing something like:

```python
if extra_kwargs:
    fcm_payload.update(extra_kwargs)

if extra_notification_kwargs:
    fcm_payload['notification'].update(extra_notification_kwargs)
```

I don't know which you'll prefer, but the library does seemingly not support enabling rich content as is. It seems this change was made  in #130, but it's definitely not supposed to be inside "notification".

**Comment by olucurious** [comment]
Fixed in https://github.com/olucurious/PyFCM/pull/189
