### ISSUE TITLE
Certificate verify failed, need to point requests to the right certificate location

### ISSUE THREAD

**Issue by capcom-r** [olucurious/PyFCM#180]
Everything works fine for me in my development environment, but I'm experiencing an error in production where everything goes through SSL. I receive this error when I run any PyFCM functions:

`routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
`
I've traced it to the fact that as PyFCM is using the `requests` package, I need to pass in the following parameter to point the request to my certificate `verify="/etc/ssl/certs/ca-bundle.crt"` everytime requests is called.

Without forking and modifying PyFCM, is there a way to set this when I make a notification function call? Or is there a way to set this globally in my code or script such that PyFCM can pull it in and apply it when it makes requests?

Edit: If there is a way to tell PyFCM to set `verify=False` that would also solve my problem, although it would do so in a less ideal manner.

**Comment by olucurious** [comment]
No, we don't have support for that at the moment
