### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by castro-miguel-1993** [olucurious/PyFCM#182]
hello friend, or who can help me, This is my code to execute:
--------------------------------------------------------------
from pyfcm import FCMNotification

push_service = FCMNotification(api_key="<api-key>")

proxy_dict = {
          "http"  : "http://127.0.0.1",
          "https" : "http://127.0.0.1",
        }

push_service = FCMNotification(api_key="<api-key>", proxy_dict=proxy_dict)

registration_id = "<device registration_id>"
message_title = "Uber update"
message_body = "Hi john, your customized news for today is ready"
result = push_service.notify_single_device(registration_id=registration_id, message_title=message_title, message_body=message_body)

print result
--------------------------------------------------------------

I have an error compiling:
`Traceback (most recent call last):
  File "C:/Users/mcastro/Documents/PyProjects/pycfm/pyfcm.py", line 2, in <module>
    from pyfcm import FCMNotification 
  File "C:\Users\mcastro\Documents\PyProjects\pycfm\pyfcm.py", line 2, in <module>
    from pyfcm import FCMNotification 
ImportError: cannot import name 'FCMNotification'`

I would like you to give me a hand, I am with python version 3.5.3
I install without problems, when I run it gives me error

**Comment by warwickprince** [comment]
Looks like your test program is called the same name as the module.  pyfcm.py

Try calling it something else as I think it's confusing 'import'.

**Comment by dhwanit15** [comment]
pip install pyfcm
