### ISSUE TITLE
Send data message to topic

### ISSUE THREAD

**Issue by Lanseuo** [olucurious/PyFCM#183]
I am trying to send a data message to the subscribers of a topic. This is my code:

```
result = push_service.multiple_devices_data_message(condition="'mytopic' in topics", data_message=data)
```

I get this error:

```
File "/.../venv/lib/python3.5/site-packages/pyfcm/fcm.py", line 305, in multiple_devices_data_message for registration_ids in registration_id_chunks:
File "/.../venv/lib/python3.5/site-packages/pyfcm/baseapi.py", line 65, in registration_id_chunks for i in xrange(0, len(registration_ids), self.FCM_MAX_RECIPIENTS):
TypeError: object of type 'NoneType' has no len()
```

How can I send a data message to a topic with this method?

**Comment by olucurious** [comment]
You should use `notify_topic_subscribers`

`result = push_service.notify_topic_subscribers(topic_name="news", message_body=message)`

**Comment by UK-JamesTaylor** [comment]
Your solution does not seem to work for myself.

`result = push_service.notify_topic_subscribers(topic_name="news", message_title=message_title, message_body=message_body, data_message = data)` 

works perfectly but modifying it to 

`result = push_service.notify_topic_subscribers(topic_name="news", data_message = data)`

Any advice?
