### ISSUE TITLE
PyFCM

### ISSUE THREAD

**Issue by Josh179** [olucurious/PyFCM#192]
I try with this code:

from pyfcm import FCMNotification
push_service = FCMNotification(api_key="XXXXXXXXX")

registration_id = "XXXXXXXX"
message_title = "Message title"
message_body = "test"
result = push_service.notify_single_device(registration_id=registration_id, message_title=message_title, message_body=message_body)
print result

and this is the result, but the notification never popup in the device...
{'multicast_ids': [xxxxxxx], 'canonical_ids': 0, 'success': 1, 'topic_message_id': None, 'results': [{u'message_id': u'xxxxxxxxx'}], 'failure': 0}

so I need to create a topic? how I can do that with pyfcm? somebody have an example in Python 2.7
I'll appreciate any kind of help

**Comment by olucurious** [comment]
@Josh179 First, your issue title doesn't depict your question and it may be misleading

Second, did you read my reply from the previous thread?

I said "You need to setup your client to display the message, same goes for topic, you have to subscribe your clients to a topic."

PyFCM helps in sending downstream messages, to display a notification, you need to write code for it on your client(app) and same goes for topic, you need to subscribe your client(app users) to a topic.

**Comment by olucurious** [comment]
What platform are you developing for? I may be able to help with code samples to guide you

**Comment by Josh179** [comment]
Hi olucurious, sorry for my clumsy question, Thanks for your answer, 
I'm using IOS swift plataform, so in the IOS app I need to add a code to subscribe the device to the Firebase and the pull all tokens with python to send the notifications? I'm really noob in all of this Push Notifications, I think your PyFCM is great but I just don't  understand how the things works.

I my Swift code I have:
@objc func refreshToken(notification: NSNotification){
         let refreshToken instanceID.instanceID.token()!
         print('*** \(refreshToken) ***)
         FBHandler()
}

and when I run the app I have a token in the console.log, is that the number that I need to send to Firebase?

**Comment by olucurious** [comment]
@Josh179 a refreshToken token is for sending message to a single device
To subscribe a device to a topic, use  `Messaging.messaging().subscribe(toTopic: “foo”)`

**Comment by Josh179** [comment]
yep, Is working now, thank you Olucurious for your help, your PyFCM is very good and it was easy to integrate it into my app, the problem was I had an error in the token registration.
