### ISSUE TITLE
parse_payload() argument error

### ISSUE THREAD

**Issue by legshort** [olucurious/PyFCM#193]
Hi there, I'm using `1.4.4` and I'm currently having below error when calling `fcm_send_single_device_daa_message()`

```python
parse_payload() argument after ** must be a mapping, not NoneType
```

I think [extra_kwargs](https://github.com/olucurious/PyFCM/blob/1.4.4/pyfcm/fcm.py#L94) should have default `{}` instead of `None`

**Comment by olucurious** [comment]
Fixed in https://github.com/olucurious/PyFCM/pull/194/commits/5325aab36d6c6a2f587e7cf339ea42d2e278f6aa
