### ISSUE TITLE
How to map result to registration_id

### ISSUE THREAD

**Issue by nicolinux** [olucurious/PyFCM#198]
Hi,

first thanks for this very useful project!

When I send multiple notifications at once, I get a result back which looks something like this:
```
{'results': [{'message_id': '0:1520980542189277%a53ccdbdf9fd7ecd'}, {'message_id': '0:1520980542189262%a53ccdbdf9fd7ecd'}], 'multicast_ids': [6189250641473490358], 'failure': 0, 'topic_message_id': None, 'success': 2, 'canonical_ids': 0}
```
However I don't know which `registration_id` maps to which `message_id`. Do I need to rely on the order of the list in `registration_ids` for that?

**Comment by romantolkachyov** [comment]
Just for example:

```
for result, device_key in zip(response['results'], registration_ids):
    pass
```

And yes, the order is the same.
