### ISSUE TITLE
How to read the data/notificaiton message in my android app? 

### ISSUE THREAD

**Issue by viji-123** [olucurious/PyFCM#199]
Hi there ,

Am using PyFCM to push messages to my android app. Am able to successfully send messages. But i am not able to retrieve those messages in my android app.

data_message = {
    "Name" : "Elsa",
    }
result = push_service.notify_single_device(registration_id=registration_id, message_body=message_body, data_message=data_message)

This is the code to push message, which is working fine.
Can someone please guide me how I can retrieve message in the android app. Basically I want to get the message and store it as a string
Thank you

**Comment by andiyulistyo** [comment]
you can get the data from method
 
` @Override
    public void onMessageReceived(RemoteMessage remoteMessage) { 

        if (remoteMessage.getData().size() > 0) {
            Map<String, String> data = remoteMessage.getData();
            **Log.d(TAG, "onMessageReceived: " + data.get("name"));** 
        }
 
    }`

**Comment by viji-123** [comment]
I used the above method. But the onMessageReceived() function doesn't get called . I dont know why. I tried by keeping the app in the foreground as well the background. In both ways the onMessageReceived doesn't get called,
One good thing is the notification is coming if i keep the app in background. But the onMessageReceived doesn't get called.

**Comment by rahulsps** [comment]
@olucurious is this issue resolved yet ? we are facing the same problem. @viji-123 what did you do finally ?

**Comment by KhyatiMehta3** [comment]
Facing the exact issue. Any updates on this?

**Comment by KhyatiMehta3** [comment]
For those who still have the same issue, 
This works for me : 
Put this code in your manifest.xml file, if you're developing on Java. 
`<service android:name=".NotificationService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
</service>`
