### ISSUE TITLE
Typo in README Example Code causes Error

### ISSUE THREAD

**Issue by aleck2** [olucurious/PyFCM#200]
In the examples of the README, there is a slight typo that causes an error: 
`notifcation_extra_kwargs` parameter should be `extra_notification_kwargs`. For the sake of readability, the variable of the same name should probably also be renamed. 
```
data_message=data_message, notification_extra_kwargs=notification_extra_kwargs)
```

**Comment by olucurious** [comment]
@aleck2 can you please send in a PR for it?
