### ISSUE TITLE
Use requests.Session to enable persistent connections

### ISSUE THREAD

**Issue by razor-1** [olucurious/PyFCM#204]
instead of calling `requests.post` etc. directly, create a Session in BaseAPI. Set headers and proxies on it, so that all requests use this (fixing a bug where proxies weren't used in all cases). Now, multiple interactions with FCM using the same `FCMNotification` instance can benefit from a persistent connection instead of re-establishing it for each request.

**Comment by razor-1** [comment]
safe to say this project is abandoned?

**Comment by olucurious** [comment]
@razor-1 nope, your PR is very much appreciated, it just took a while to review.
It's merged already
