### ISSUE TITLE
Client uses legacy FCM HTTP server protocol with invalid priority param

### ISSUE THREAD

**Issue by nmanoogian** [olucurious/PyFCM#206]
There is an [existing issue](https://github.com/olucurious/PyFCM/issues/165) to implement the [new FCM HTTP API](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages). This is good, but in the meantime, there is an issue with the current legacy client regarding priority.

The [current legacy API](https://firebase.google.com/docs/cloud-messaging/http-server-ref) specifies that the `priority` field should be set in the top-level object. PyFCM seemed to have been doing that before PR #171 . #171 seems to cite the new HTTP API but the rest of the implementation continues to use legacy API which specifies the `priority` field inside of the `android` object.

It's not clear to me why this issue did not surface for our team until recently. It's possible that perhaps FCM was accepting `priority` inside of the `android` object and recently stopped. The documentation also mentions:

> By default, notification messages are sent with high priority, and data messages are sent with normal priority.

Until #194, PyFCM was sending `notification` as an empty object if no notification keys were specified. Our team uses a data payload exclusively in our app. FCM may have previously been treating an empty object as a "notification message" and setting the default priority to "high." It difficult to confirm, however, and FCM does not seem to be exhibiting this behavior any more.

In any case, the changes introduced in #171 should be reversed until the new FCM HTTP API is fully implemented. Until then, the `low_priority` parameter for this library's functions will be silently ignored.

**Comment by toddhodes** [comment]
+1.  Also, confirmed high priority isn't working, from the client perspective, using RemoteMessage.getPriority() and getOriginalPriority() in onMessageReceived()

**Comment by ianbrind** [comment]
Also, confirmed high priority is not working on Android.
the library looks to be using the legacy API but the implementation of priority seems to be following the v1 spec.
https://github.com/olucurious/PyFCM/blob/244e9ba334471d0117d4bac343e34573b7e09ab2/pyfcm/baseapi.py#L126-L129

**Comment by marataziat** [comment]
```
As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features. See the migration guide to learn more.
```
Will it cause any issues to the library?
