### ISSUE TITLE
What's the difference with the Firebase Admin SDK?

### ISSUE THREAD

**Issue by robertu7** [olucurious/PyFCM#208]
Firebase Admin SDK is maintained by Firebase. Should it be used instead of PyFCM?

https://firebase.google.com/docs/admin/setup

**Comment by romantolkachyov** [comment]
@RoberMac did you found an answer? Is it using modern API and should we warn new users to force them to use google client library instead of this one?

**Comment by Bartvaderkin** [comment]
@aksswami Looks like sending push notifications to multiple registration ids is now supported in the Admin APIs: https://firebase.google.com/docs/cloud-messaging/send-message#send-messages-to-multiple-devices
