### ISSUE TITLE
support "mutable_content" parameter 

### ISSUE THREAD

**Issue by folt** [olucurious/PyFCM#213]
Hi 
I need to send the "mutable_content" field but it is not in the available parameters. Was it possible to add his support?

https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json

**Comment by folt** [comment]
> Hello,
> 
> you can add extra parameters like that:
> 
> ```python
> extra_kwargs = {
>     "mutable_content": True
> }
> 
> push_service.notify_single_device(
>     registration_id=registration_id,
>     data_message=data_message,
>     content_available=True,
>     extra_kwargs=extra_kwargs
> )
> ```
> 
> I hope that was helpful for you!

Thank! I did about that when I read the library code.

**Comment by romantolkachyov** [comment]
Yeah, I found it in sources too. We need a better docs #216
