### ISSUE TITLE
Documentation and Tests

### ISSUE THREAD

**Issue by Lanseuo** [olucurious/PyFCM#216]
Hello,

what do you think about a documentation for the library?
Can I add a folder called `docs`? I would use Sphinx to create the documentation.

I would also add some tests to the library. That makes it much more comfortable too develop new features without breaking stuff.
Can I use [pytest](https://docs.pytest.org/en/latest/) for that?

**Comment by olucurious** [comment]
@Lanseuo sure, that would be awesome
