### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by arthurstomp** [olucurious/PyFCM#22]
Got this message when I tried to add the pyfcm in my INSTALLED_APPS
`
File "/home/<username>/.pyenv/versions/3.4.2/lib/python3.4/site-packages/pyfcm/fcm.py", line 1, in <module>
    from baseapi import BaseAPI
ImportError: No module named 'baseapi'
`

**Comment by olucurious** [comment]
This has been fixed in a previous commit, install the latest version with: pip install git+git://github.com/olucurious/PyFCM.git
