### ISSUE TITLE
Missing android_channel_id in baseapi.py

### ISSUE THREAD

**Issue by fastlorenzo** [olucurious/PyFCM#225]
Although android_channel_id has been added in pyfcm.py, it appears that it's not handled in baseapi.py and thus not sent correctly to FCM.

Quick workaround I used for the moment: 
        extra_notification_kwargs={'android_channel_id':topic_name}

I'll try to make a PR later to fix it.

**Comment by joshuakoh7** [comment]
Still running into this problem in 2020. Both multiple and single device pushes.
