### ISSUE TITLE
How do i get all registration_ids

### ISSUE THREAD

**Issue by codingsett** [olucurious/PyFCM#235]
Hi i have been looking for hours for this since i want to send notifications to all my devices but i see i need notification ids. How do i get that using this package? Any help would be appreciated thanks!

**Comment by sunnyseeds** [comment]
I think you may be referring to the device token? You need to obtain that from the device or devices and store it somewhere such as a database and then you can use this.

**Comment by olucurious** [comment]
You need to subscribe your users to a topic and send the notification to the topic
