### ISSUE TITLE
Is there a way to send notification to a topic?

### ISSUE THREAD

**Issue by KwanWaiChung** [olucurious/PyFCM#237]
I am aware that we can send a message to a topic, but can we send a notification to a topic? thanks

**Comment by Lanseuo** [comment]
Sure, that's possible:

```python
push_service = FCMNotification(api_key=api_key)

push_service.notify_topic_subscribers(
    topic_name=topic,
    message_title=title,
    message_body=message,
)
```

**Comment by sachinkumar502** [comment]
thats not working it show success but mobile side didnt receive anything.

**Comment by marianlukac** [comment]
Is this project still living? I have the same problem as @sachinkumar502 ...
