### ISSUE TITLE
How can I set badge variable and send the message？

### ISSUE THREAD

**Issue by akira32chen** [olucurious/PyFCM#253]
I have a problem on iOS device. That is the message sends to FCM does not have the badge parameter. But my user hopes the badge works on iOS device. Does somebody know how to send the message with badge variable to FCM？

**Comment by IRemsha** [comment]
Set parameter badge for __notify_multiple_devices__
```
push_service.notify_multiple_devices(
            registration_ids=chunk,
            message_title=title,
            message_body=body,
            data_message=data,
            sound=False,
            badge=3
        )
````
