### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by bhaskar8088** [olucurious/PyFCM#257]
I tried to use like below

push_service = FCMNotification(api_key)
push_service.notify_multiple_device(registration_ids=registration_ids, message_title=message_title,
            message_body=message_body, data_message=data_message, sound="Default")

I added sound="Default" as last parameter of that function. But mobile not making any sounds even though notification is coming.

Any idea how to fix this? Thanks

**Comment by Luckius** [comment]
Hello any help here will be approciated because even me iam facing the same problem!! please help

**Comment by 000xuandu** [comment]
`sound="default"` is working for me.

**Comment by TheBestMoshe** [comment]
`sound="Default"` Works for me as well
