### ISSUE TITLE
How to add key "priority" and value HIGH in json

### ISSUE THREAD

**Issue by 000xuandu** [olucurious/PyFCM#259]
I have the following json:

```
{ "registration_ids": ["TOKEN"],

"priority": "high", // this line

"data" : {
        "body" : "The first message from the React Native and Firebase",
        "title" : "a' Event"
    }
}
```
This helps show popup notifications for android 8+. Without this key, the notification will not appear.
The "low_priority" key is similar to the "priority" in my example?
How to add "priority" when sending from PyFCM. Thank you.

**Comment by sachinkumar502** [comment]
facing same issue , it show success but mobile side didnt show anything.
