### ISSUE TITLE
Can't install any version greater than 0.0.4 from PyPI

### ISSUE THREAD

**Issue by drakedevel** [olucurious/PyFCM#26]
Running `pip install pyfcm` installs version `0.0.4` when the latest on PyPI is `0.0.9`. Running `pip install pyfcm==0.0.9` fails with:

```
$ pip install pyfcm==0.0.9
Collecting pyfcm==0.0.9
  Could not find a version that satisfies the requirement pyfcm==0.0.9 (from versions: 0.0.1, 0.0.2, 0.0.4)
No matching distribution found for pyfcm==0.0.9
```

I believe this is because `0.0.4` is the latest version to have a source distribution uploaded -- you can see the file is present at https://pypi.python.org/pypi/pyfcm/0.0.4, but not at https://pypi.python.org/pypi/pyfcm/0.0.9.

**Comment by olucurious** [comment]
Case resolved.
Thanks.
