### ISSUE TITLE
ios custom noti sound with caf

### ISSUE THREAD

**Issue by ppkpp** [olucurious/PyFCM#264]
I tested cordova-firebasex and pyfcm. Custom notification sound for android work perfectly . But there is no documentation for ios custom notification sound with caf file.Is there any ways to make ios custom notification sound with pyfcm?

**Comment by danemco** [comment]
I'm having the same issue and would like help here.

As for custom notification sounds for Android, I can get them to work on Android 6, but not Android 8+. @ppkpp were you able to get custom notification sounds to work for newer Android?
