### ISSUE TITLE
web_push for desktop notifications and click action

### ISSUE THREAD

**Issue by axebelk** [olucurious/PyFCM#265]
Hello,

Can you make it to work the web_push object to be send along with notification data? 
Check here: https://firebase.google.com/docs/cloud-messaging/js/receive
"webpush": {
      "fcm_options": {
        "link": "https://dummypage.com"
      }
    }

**Comment by tradingstratagem** [comment]
I have the same problem, can anyone have the solution? I tried to add the payload using  extra_kwargs but it doesn't work

**Comment by tperraut** [comment]
@tradingstratagem @axebelk did you try `extra_notification_kwargs` instead ? 
```python
push_service.notify_multiple_devices(
    registration_ids=tokens,
    message_title=title,
    message_body=body,
    extra_notification_kwargs={'link': "https://mydomain.com/redirect_path"}
)
```

**Comment by lordzouga** [comment]
> @tradingstratagem @axebelk did you try `extra_notification_kwargs` instead ?
> 
> ```python
> push_service.notify_multiple_devices(
>     registration_ids=tokens,
>     message_title=title,
>     message_body=body,
>     extra_notification_kwargs={'link': "https://mydomain.com/redirect_path"}
> )
> ```

doesn't work. This needs webpush object to be on the same level as the message body.f
