### ISSUE TITLE
Confusion AUTHORS.rst

### ISSUE THREAD

**Issue by alexsukhrin** [olucurious/PyFCM#272]
I It seems confusion.
The file CONTRIBUTING.rst describes the procedure for developers.
I did not find this file in the project.
I think this needs to be fixed.
Since we are specifying the name in CHANGES.rst, 
I think it would be superfluous to have the file and specify the name in AUTHORS.rst.
I suggest deleting the 5 element in the CONTRIBUTING.rst file in the Overview list.
@olucurious And what do you think?

**Comment by olucurious** [comment]
Please go ahead with a PR
