### ISSUE TITLE
Error: type object 'Retry' has no attribute 'DEFAULT_ALLOWED_METHODS'

### ISSUE THREAD

**Issue by mawkee** [olucurious/PyFCM#282]
This happens on 1.5.0, and started today. The relevant code is pretty simple and shouldn't be problematic, in theory:

```python
fcm = pyfcm.FCMNotification(api_key=conf["google"]["fcm"]["key"])
```

Downgrading to 1.4.9 or 1.4.7 solves the problem

**Comment by olucurious** [comment]
bug reverted

**Comment by mawkee** [comment]
It looks like the same thing is happening once again on 1.5.2 (reverting to 1.5.1 solved the problem)

**Comment by olucurious** [comment]
@mawkee can you please try the develop branch and confirm if it works
You should also check this thread https://github.com/olucurious/PyFCM/pull/280#issuecomment-865897247 for an ongoing conversation about it

**Comment by mawkee** [comment]
@olucurious I saw the proposed fix and I tried manually upgrading urllib3 to 1.26.0+, and that solved the problem. As far as I was able to test (can't test the whole implementation since my setup relies on pypi) things are looking good.

**Comment by olucurious** [comment]
Just made a new PyPi release
