### ISSUE TITLE
Badge is not updated if the app is open

### ISSUE THREAD

**Issue by IRemsha** [olucurious/PyFCM#284]
Badge responds to updates when notifications arrive in the minimized app. But when I want to go into it and read all the notifications and set badge=0 updates do not occur. Also, I want to clarify with you why in the documentation badge has the type string.

Any ideas?

**Comment by jeffersonaaron25** [comment]
Still clueless on whether this is possible to do with pyfcm. Badge count resets as expected when app is closed or in background but when the app is open/in foreground (which is when I call an api to reset the badge count), it doesn't work.

Please advice!
