### ISSUE TITLE
Being explicit about your versioning strategy

### ISSUE THREAD

**Issue by lukeburden** [olucurious/PyFCM#285]
Hi @olucurious - I'm writing a [minimalistic Django FCM lib](https://github.com/lukeburden/django-fcm-devices) and would like to set dependencies as relaxed as possible to avoid conflicts with other libs.

From your readme it isn't clear what versioning strategy you're using. Since you introduced backwards incompatible changes in a minor release (1.4.0 up from 1.3.1) I assume you're not using [semantic versioning](https://semver.org/)? Is it safe to assume that within minor versions there are not backward compatible changes?

Thanks for your efforts!

**Comment by olucurious** [comment]
Hi @lukeburden, thank you for your work on the Django lib.
The bump from 1.3.1 to 1.4.0 wasn't really clearly planned out, but I want to assure you that the minor versions are backward compatible, at least from v1.4.0

**Comment by lukeburden** [comment]
OK, good to know. It'd be sweet if you committed to semver on your main readme! I'll set the deps accordingly. Thanks for your response @olucurious.
