### ISSUE TITLE
SyntaxError: getting error while pytesting in python 2.7

### ISSUE THREAD

**Issue by dooyeoung** [olucurious/PyFCM#295]
type annotation throws an error in python 2.7.
Unfortunately I can't upgrade python. So I have to use python 2.7.
I think there are quite a few people in the same situation as me.
I think this issue can be easily solved

https://github.com/olucurious/PyFCM/blob/master/pyfcm/fcm.py#L564

**Comment by pokoli** [comment]
I think this can be closed as PR is merge: /cc @olucurious
