### ISSUE TITLE
Receiving FCM notifications

### ISSUE THREAD

**Issue by yaroslaff** [olucurious/PyFCM#298]
Hello!

Is it possible to *receive* FCM notification with PyFCM or any other python library?

I have 'server' app which should notify 'clients' about some events. Currently I'm using webhooks (each client app runs built-in webserver). This looks too heavy and works only when client has public IP address. But since android with FCM works well even behind NAT, I'm thinking about using FCM for this purpose. Do you think it's possible?

**Comment by olucurious** [comment]
You can only receive messages via an Android, iOS or web client https://firebase.google.com/docs/cloud-messaging#how-does-it-work
