### ISSUE TITLE
registration_id of notify_single_device does not work with a str input

### ISSUE THREAD

**Issue by aysonje** [olucurious/PyFCM#3]
The `FCMNotification.notify_single_device` seems to be parsing its `registration_id` wrong. This doesn't work:

```
push_service.notify_single_service(registration_id=reg_id, ...)
```

but this works:
```
push_service.notify_single_service(registration_id=[reg_id], ...)
```

**Comment by olucurious** [comment]
Thanks for pointing this out, shows we really need to write unit tests.
The issue has been fixed in the latest commit.

Cheers.

PS: I'll wait for you to confirm the fix is working before closing the issue
You can install the update with pip install git+git://github.com/olucurious/PyFCM.git

**Comment by aysonje** [comment]
Thanks for the fix! I forgot to watch this repo so I didn't receive any notifications.
