### ISSUE TITLE
Any plans for migrating from lagecy HTTP to HTTPv1 ?

### ISSUE THREAD

**Issue by davit555** [olucurious/PyFCM#301]

**Comment by rezaul99** [comment]
Any plans for migrating from Legacy HTTP to HTTPv1?

**Comment by olucurious** [comment]
@rezaul99 we are looking for contributors, can you assist?

**Comment by jonesnc** [comment]
@olucurious If you're looking for contributors, I'd also be interested in helping out.

**Comment by olucurious** [comment]
Hi @jonesnc thanks for expressing interest in contributing.
I'm thinking of wrapping around the firebase-admin library (https://firebase.google.com/docs/reference/admin/python/firebase_admin.messaging), 
if you have some time can you please send a draft PR to the develop branch 🙏🏾

**Comment by davidemerritt** [comment]
@olucurious can you help explain what added functionality/value add pyfcm has/added over using firebase_admin.messaging directly? I am trying to understand what added functionality/logic I've been using with pyfcm that may not be as explicit with the direct firebase_admin.messaging functions?

**Comment by davidemerritt** [comment]
I ended up migrating to the [firebase_admin SDK](https://github.com/firebase/firebase-admin-python) library to support FCM sending for the migration.

I have seen a big uptick in latency for topic based push notifications and a drop-off in delivery rate and users reporting more dropped messages. Has anyone else seen this as part of the migration off of the legacy FCM endpoints?

**Comment by jonesnc** [comment]
I ended up moving to [`fcm-django`](https://github.com/xtrinch/fcm-django).

**Comment by olucurious** [comment]
Done https://github.com/olucurious/PyFCM/releases/tag/2.0.1
