### ISSUE TITLE
Default priority should be normal, not high

### ISSUE THREAD

**Issue by c4talyst** [olucurious/PyFCM#309]
### Current behaviour
* `low_priority=True`: FCM is called with `normal` priority
* `low_prority=False`: FCM is called with `high` priority
* The default is `high` priority

### Expected behaviour
* Priority should default to `normal`
* The client should be able to adjust to `high` priority
* `low` priority doesn't exist on the [FCM API](https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream-http-messages-json)

### Rationale
* High priority has quotas to prevent abuse (`QuotaExceededError: Topic quota exceeded.`) & (`requests.exceptions.HTTPError: 429 Client Error: Too Many Requests`
* It's confusing that `low` means `normal` and `not low` means `high`; when you might assume that `not low` means normal. 

Thanks for a great library :) We use it A LOT

**Comment by c4talyst** [comment]
Fixed or just closing out old issues?

Is this clean up somehow related to -> https://firebase.google.com/docs/cloud-messaging/migrate-v1 ?

**Comment by olucurious** [comment]
Yes, priority is now Android specific and the default is no longer HIGH, according to the doc here: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages
