### ISSUE TITLE
Will PyFCM be affected by API discontinuance

### ISSUE THREAD

**Issue by dwaynez** [olucurious/PyFCM#313]
I received the note below from Google. Does anybody know if PyFCM will be affected, and if so are there plans to address it?

[Firebase APIs 2.pdf](https://github.com/olucurious/PyFCM/files/11808506/Firebase.APIs.2.pdf)

**Comment by stabacco** [comment]
Yes, i believe they are affected: 
These are the warning i'm seeing in my project: 

```
    Your recent usage of impacted APIs/features: Server Keys
    Your recent usage of impacted APIs/features: Legacy HTTP protocol
```

**Comment by mleech** [comment]
If PyFcm does not get updated to handle this then it looks like the best approach may be to move to firebase-admin (https://github.com/firebase/firebase-admin-python) as fcm-django has done (https://github.com/xtrinch/fcm-django).

**Comment by senenpalanca97** [comment]
Any news with this?

**Comment by davidemerritt** [comment]
I'd also like to know ahead of time if there is any plan to address this or if it will require using fcm-django or a different implementation entirely?

**Comment by olucurious** [comment]
@senenpalanca97 @davidemerritt does anyone want to offer help by sending a draft PR?

**Comment by yossivainshtein** [comment]
any news on this?
firebase will soon deprecate the old API if i understand correctly

**Comment by davidemerritt** [comment]
I ended up migrating to the [firebase_admin SDK](https://github.com/firebase/firebase-admin-python) library to support FCM sending for the migration.

I have seen a slight drop-off in delivery rate and users reporting more dropped messages. Has anyone else seen this as part of the migration off of the legacy FCM endpoints? May be unrelated but the timing is suspicious.

**Comment by Subhrans** [comment]
Hi All,
I have updated this pyfcm package with v1 endpoints thats google mentioned. You guys can check below pull request and let me know if anything changes required.
https://github.com/olucurious/PyFCM/pull/319

I hope we will release this before google remove legacy dependencies.
Thanks

FYI @olucurious

**Comment by olucurious** [comment]
Migration done - https://github.com/olucurious/PyFCM/releases/tag/2.0.1
