### ISSUE TITLE
cannot work behind proxy

### ISSUE THREAD

**Issue by zichong** [olucurious/PyFCM#32]
in baseapi class, request is sent using request.send.
```python
response = requests.post(self.FCM_END_POINT, headers=self.request_headers(), data=payload, verify=True)
```
so there's no way to config proxy but to modify the code in base class directly.

**Comment by olucurious** [comment]
Thanks for pointing this out, the issue has been fixed in the latest commit.
Check for updated README for instructions on how to use proxies.
You can install the update with pip install git+git://github.com/olucurious/PyFCM.git OR pip install pyfcm --upgrade

Cheers.
