### ISSUE TITLE
Documentation indicates just the service file is needed:

### ISSUE THREAD

**Issue by LawrenceK** [olucurious/PyFCM#330]
Documentation for indicates just the service file is needed:
FCMNotification(service_account_file=config.firebase["service_file"])

But run time reports requires project_id

    pushClient = FCMNotification(service_account_file=config.firebase["service_file"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseAPI.__init__() missing 1 required positional argument: 'project_id'

**Comment by olucurious** [comment]
Thanks, fixed in [this](https://github.com/olucurious/PyFCM/commit/871dc7a5c9e159f01b6d01915329b1027e62646f) commit
