### ISSUE TITLE
The options click_action and low_priority not available anymore.

### ISSUE THREAD

**Issue by jarzac** [olucurious/PyFCM#341]
The following options when sending messages using push_service.notify are not available anymore.
    
 - click_action
 - low_priority
 
 Where these renamed or moved somewhere else?

**Comment by Niccari** [comment]
Starting with PyFCM v2, platform-specific parameters are specified in android_config and apns_config. Fields in Android are defined in the FCM HTTP v1 API [AndroidConfigs](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidconfig).

Thus, click_action and low_priority can be specified as follows.

```
result = fcm.notify(
    topic_name="news",
    notification_body=message,
    android_config={
        "priority": "normal",    # "high" for high priority
        "notification": {
            "click_action":"YOUR_ACTION"
        }
    }
)
```

**Comment by olucurious** [comment]
Check this section - https://github.com/olucurious/PyFCM?tab=readme-ov-file#extra-argument-options
