### ISSUE TITLE
pyfcm.errors.FCMServerError: FCM server error: Unexpected status code 500. The server might be temporarily unavailable.

### ISSUE THREAD

**Issue by wogno** [olucurious/PyFCM#363]
I upgrade to pyfcm==2.0.7 but still get the same error
What is real problem. 

![Capture d’écran 2024-10-15 à 13 00 46](https://github.com/user-attachments/assets/be83caaf-1d09-4693-8e63-2e7e0e24b1c0)
![Capture d’écran 2024-10-15 à 13 01 07](https://github.com/user-attachments/assets/4e961ddc-a9f9-4a1a-b0bb-2d4f9ea61ff4)

**Comment by newengine** [comment]
Same error

**Comment by wogno** [comment]
@newengine Error was fixed, after way one 1 day after generate firebase.json file
