### ISSUE TITLE
Problem sending notification

### ISSUE THREAD

**Issue by mtsimoni** [olucurious/PyFCM#37]
I have a problem when I try to send a notification with this code:

import database
from sqlalchemy.orm import Session
from pyfcm import FCMNotification

base = database.Base
engine = database.engine
session = Session(engine)

Client = base.classes.cliente
row = session.query(Client).filter(Client.id == 40).one()
last_fcm = row.last_fcm_id

key_file = open("d:\\python34\\eturn\\key\\eturn-df72e3592e73.json", "r")
key = key_file.read()

push_service = FCMNotification(api_key=key)
registration_id = last_fcm
message_title = "update"

data_message = {
    "queue" : "1234",
    "current" : "157",
    "aat" : "300"
}

result = push_service.notify_single_device(registration_id=registration_id, message_title=message_title, data_message=data_message)
print(result)

This is the error:

Traceback (most recent call last):
  File "D:/Python34/eturn/fcm_notifier.py", line 41, in <module>
    result = push_service.notify_single_device(registration_id=registration_id, message_title=message_title, data_message=data_message)
  File "D:\Python34\eturn\lib\site-packages\pyfcm\fcm.py", line 84, in notify_single_device
    return self.send_request([payload])
  File "D:\Python34\eturn\lib\site-packages\pyfcm\baseapi.py", line 198, in send_request
    raise FCMServerError("FCM server is temporarily unavailable")
pyfcm.errors.FCMServerError: FCM server is temporarily unavailable

Process finished with exit code 1

I'm working with pyfcm 1.0.0 and python 3.4

Checking the code from baseapi.py I found and modified this for know the real exception:

    def send_request(self, payloads=None):

        for payload in payloads:
            response = requests.post(self.FCM_END_POINT, headers=self.request_headers(), data=payload)
            if self.FCM_REQ_PROXIES:
                response = requests.post(self.FCM_END_POINT, headers=self.request_headers(), data=payload, proxies=self.FCM_REQ_PROXIES)
            if response.status_code == 200:
                return self.parse_response(response)
            elif response.status_code == 401:
                raise AuthenticationError("There was an error authenticating the sender account")
            elif response.status_code == 400:
                raise InternalPackageError("Please create a new github issue describing what you're doing")
            else:
                print("Exception: ", response.status_code)     # Line added
                raise FCMServerError("FCM server is temporarily unavailable")

Then I get the exception 411.

This is:
       411 - Length Required

I am doing something wrong?

**Comment by olucurious** [comment]
Are you sure you're not running the program behind a proxy server?

**Comment by mtsimoni** [comment]
Thanks for your answer. 
I'm working on Windows behind NAT. 
I think I'm not behind any proxy
I will move this program to Debian to test how it works.
