### ISSUE TITLE
Any API error results in not-very-helpful InternalPackageError

### ISSUE THREAD

**Issue by enkore** [olucurious/PyFCM#41]
E.g. the FCM API responds with 400 and a JSON body like `{'error': 'MessageTooBig'}` results in the rather unclear exception `pyfcm.errors.InternalPackageError: Please create a new github issue describing what you're doing`

**Comment by olucurious** [comment]
Fixed in https://github.com/olucurious/PyFCM/commit/8b038dd4033ac48205c82a75dbd46f9c00016336

**Comment by enkore** [comment]
Thanks!
