### ISSUE TITLE
Starting new HTTPS connection

### ISSUE THREAD

**Issue by vahidsadeghi213** [olucurious/PyFCM#44]
Hi,
I used pyfcm in order to broadcast notification on android devices. in log following line display for every request : 
 Starting new HTTPS connection (1): fcm.googleapis.com

But in apple push notification, it uses sockets. it seems FCM support socket connection to make it live for bulk request.

Do you have any plane in order to support socket connection?

**Comment by michaelotto** [comment]
I would like to see that, too. Sending a couple thousand push notifications takes way too long like this.

**Comment by olucurious** [comment]
@michaelotto I'll advice you run the push notification in a separate thread

**Comment by michaelotto** [comment]
I'm doing that already. Still, a SSL negotioation handshake for every client/push notification is an insane overhead ;-)

**Comment by vahidsadeghi213** [comment]
Right now I use separate threads to handle push notification, it is working fine but it'll be better if it uses Socket in order to bypass Http connection overhead.

**Comment by olucurious** [comment]
Sockets are not always supported on all platform, e.g GAE, it's going to break for the users on those platforms
