### ISSUE TITLE
ChunkedEncodingError occurs when I'm trying to send push notification from our GAE server

### ISSUE THREAD

**Issue by Avinash-Raj** [olucurious/PyFCM#48]
` ChunkedEncodingError: ('Connection broken: IncompleteRead(14 bytes read)', IncompleteRead(14 bytes read))`

**Comment by BasmaElias** [comment]
I have the same problem , can you tell me how did you fix it ?

**Comment by Avinash-Raj** [comment]
@BasmaElias That's my mistake. I failed to give the firebase server api key.,

**Comment by BasmaElias** [comment]
ok , thank you
