### ISSUE TITLE
How to send high priority message?

### ISSUE THREAD

**Issue by bogomazov** [olucurious/PyFCM#49]
I wold like to send a high priority message, is it set up by default?

**Comment by olucurious** [comment]
YES!

**Comment by bogomazov** [comment]
We experience 5-10 min delays with delivering messages, it is not instant. Firebase docs specify that there is 2 types `normal` and `high`. I assume that by default we use `high` property.

**Comment by olucurious** [comment]
In the code (https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L138) the priority is high by default
