### ISSUE TITLE
Cannot set badge without also including a message_body

### ISSUE THREAD

**Issue by Atheros1** [olucurious/PyFCM#51]
But I don't want to include a message body, I just want to set the badge count. Use cases for this abound. Currently I've had to fork PyFCM and do like this:

    from PyFCM.pyfcm import BaseAPI
    import json
    import config

    base_service = BaseAPI(api_key=config.FCM_APIKey)
    
    pushToken = "big-long-private-push-token-asdofiauusifaosdfuadfnua9sd8fnu9asd8f"
    fcm_payload = dict()
    fcm_payload['priority'] = 'high'
    fcm_payload['notification'] = {}
    fcm_payload['notification']['badge'] = 5
    fcm_payload['to'] = pushToken
    payload = (json.dumps(fcm_payload, separators=(',', ':'), sort_keys=True)
    .encode('utf8'))
    
    print base_service.send_request([payload])

**Comment by olucurious** [comment]
Can you kindly make a fix and submit a PR? It will be much appreciated
