### ISSUE TITLE
Certain features fail silently if the programmer uses the wrong type

### ISSUE THREAD

**Issue by Atheros1** [olucurious/PyFCM#52]
One example

    if data_message and isinstance(data_message, dict):
        fcm_payload['data'] = data_message

another example:

    if time_to_live and isinstance(time_to_live, int):
        fcm_payload['time_to_live'] = time_to_live

It would be better to throw an exception or at least a big warning to stderr so that the programmer can do something about the fact that they used the wrong type.

**Comment by olucurious** [comment]
Can you kindly make a fix and submit a PR? It will be much appreciated
