### ISSUE TITLE
Topics messages doesn't work

### ISSUE THREAD

**Issue by israelR** [olucurious/PyFCM#54]
Hi,
I tried to send a topic message with this configuration:
result = push_service.notify_topic_subscribers(topic_name="messages", message=message) 
I get  -
{'failure': 0, 'canonical_ids': 0, 'success': 1, 'multicast_id': None, 'results': []}
BUB .... NO MESSAGES FOUND ON FCM DB.
Please advise.

**Comment by olucurious** [comment]
The message has been sent, you need to subscribe your app to the topic

**Comment by israelR** [comment]
10x
It's something on my app.
I checked it with direct FCM services and it's also not working
