### ISSUE TITLE
[Question] Should a notifcation be sent in 2 minutes ?

### ISSUE THREAD

**Issue by marianpavel** [olucurious/PyFCM#56]
Hi, I searched for something similar but I couldn't find.
I implemented the library on my server and successfully sent out a notification, it takes from 1 to 2 minutes to send a notification. Is this normal ? Sending a notification from Firebase console works instantly. There should be only a short delay.

Best regards,
Marian Pavel

**Comment by olucurious** [comment]
That will most probably be an issue on fcm api server not the library
