### ISSUE TITLE
Support for content_available flag

### ISSUE THREAD

**Issue by ajmcgarry** [olucurious/PyFCM#57]
I do not see any support for the content_available flag for sending gcm/fcm messages to ios devices

**Comment by olucurious** [comment]
If you don't send the message body, it means you're sending content_available instead. Look at https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L181

**Comment by ajmcgarry** [comment]
They are not mutually exclusive.
On iOS the content_available flag should be used to wake the device from a background state. 
If there is a message included, IOS will automatically display the notification without requiring you to fetch any data from an upstream source.
If there is no message included, IOS will display nothing (silent notification) and the device gets some background CPU time for you to fetch data should you need.

**Comment by olucurious** [comment]
That's the point "If there is a message included, IOS will automatically display the notification without requiring you to fetch any data from an upstream source.", so why would you want to send content_available with a message?

**Comment by deceze** [comment]
Setting `content_available = True` seems to prevent the invocation of background service workers when pushing to web browsers (see https://github.com/firebase/quickstart-js/issues/71). It is a bug to set it to `True` when no body is present; for browsers we *want* no body _and_ no `content_available`.

**Comment by olucurious** [comment]
UPDATED and FIXED here: https://github.com/olucurious/PyFCM/releases/tag/1.2.0
