### ISSUE TITLE
InternalPackageError when sending bulk message to an empty queryset

### ISSUE THREAD

**Issue by xtrinch** [olucurious/PyFCM#60]
>   File "/home/vagrant/files/localove/management/commands/send_test_notification.py", line 13, in handle
>     devices.send_message(data={"test": "test"}, badge=5)
>   File "/home/vagrant/files/fcm-django/fcm_django/models.py", line 52, in send_message
>     **kwargs
>   File "/home/vagrant/files/fcm-django/fcm_django/fcm.py", line 51, in fcm_send_bulk_message
>     **kwargs
>   File "/home/vagrant/env/lib/python3.4/site-packages/pyfcm/fcm.py", line 190, in notify_multiple_devices
>     return self.send_request([payload])
>   File "/home/vagrant/env/lib/python3.4/site-packages/pyfcm/baseapi.py", line 200, in send_request
>     raise InternalPackageError("Please create a new github issue describing what you're doing")
> pyfcm.errors.InternalPackageError: Please create a new github issue describing what you're doing

Basically what I was trying to do is send bulk message to an empty queryset. I do believe there are use cases when there are simply no devices that match the query and I think it should not be left to the user to check if the queryset count is larger than zero.

**Comment by olucurious** [comment]
Update the library 

pip install pyfcm --upgrade

**Comment by BojanKogoj** [comment]
> pyfcm==1.2.3 

No change, still throws an error

**Comment by olucurious** [comment]
Okay, what's the new error message?
