### ISSUE TITLE
Wheel for py3.5 doesn't contain tornado extentions

### ISSUE THREAD

**Issue by h4** [olucurious/PyFCM#62]
I try to import `TornadoFCMNotification` in this way

```py
from pyfcm import TornadoFCMNotification
```

but it fails with 

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TornadoFCMNotification'
```

after short investigation I realised that `pip install pyfcm` don't install `extensions` dir in `lib/python3.5/site-packages/pyfcm/`.

**Comment by olucurious** [comment]
Removed Tornado handler for now
