### ISSUE TITLE
Sound parameter

### ISSUE THREAD

**Issue by galileoguzman** [olucurious/PyFCM#64]
The API for FCM has parameter to send sound opction on mobile apps, but with pyFCM I could not found the option to send.

**Comment by olucurious** [comment]
Just add sound as a parameter, see here for reference: https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L97

**Comment by mrugeshtank** [comment]
Just Set true here
https://github.com/olucurious/PyFCM/blob/master/pyfcm/fcm.py#L11
