### ISSUE TITLE
Sending notification to over 1000+ devices

### ISSUE THREAD

**Issue by michal-michalak** [olucurious/PyFCM#66]
Did any of you try to send notification to 1000+ (e.g. 2450 tokens = 3 chunks) devices and more ?

From what I see method notify_multiple_devices splits that kind of request into chunks.
In reality it sends notification to only 1000 first registration tokens cause  send_request method returns parsed response.

    def send_request(self, payloads=None):

        for payload in payloads:
            response = requests.post(self.FCM_END_POINT, headers=self.request_headers(), data=payload)
            if self.FCM_REQ_PROXIES:
                response = requests.post(self.FCM_END_POINT, headers=self.request_headers(), data=payload, proxies=self.FCM_REQ_PROXIES)
            if response.status_code == 200:
                return self.parse_response(response)
            elif response.status_code == 401:
                raise AuthenticationError("There was an error authenticating the sender account")
            elif response.status_code == 400:
                raise InternalPackageError(response.text)
            else:
                raise FCMServerError("FCM server is temporarily unavailable")

**Comment by michal-michalak** [comment]
I am fully aware that we need split it into chunks, but.. the problem is that you won't be able to send remaining 1450 notifications. That will "break" after parsing first response. You should probably append parsed response to list and return that list after for loop.

or should we.. ?

Split it into chunks by yourself and call notify_multiple_devices method 3 times - but that is not the point. Am I right ?

**Comment by olucurious** [comment]
In the notify_multiple_devices method, see here: https://github.com/olucurious/PyFCM/blob/master/pyfcm/fcm.py#L146

if len(registration_ids) > self.FCM_MAX_RECIPIENTS:
            payloads = list()
            registration_id_chunks = self.registration_id_chunks(registration_ids)
            for registration_ids in registration_id_chunks:
                # appends a payload with a chunk of registration ids here
                payloads.append(self.parse_payload(registration_ids=registration_ids,.....)

Which means you don't need to call the method 3 times, it splits into chunks by using this method https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L75 and then loops over the chunks while sending the request

**Comment by olucurious** [comment]
There was a little misunderstanding but I eventually get what you were saying.
It has been fixed in the latest update here https://github.com/olucurious/PyFCM/blob/master/pyfcm/fcm.py#L275, https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L175 and https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L177

**Comment by michal-michalak** [comment]
Thanks for quick reaction :) but .. there is one more thing. You made similar mistake once again: https://github.com/olucurious/PyFCM/blob/master/pyfcm/baseapi.py#L198
You are returning dict inside for loop, instead of list (that contains parsed dicts) after for loop.

**Comment by olucurious** [comment]
Fixed here https://github.com/olucurious/PyFCM/blob/develop/pyfcm/baseapi.py#L200

I can't appreciate you enough, and it will be helpful if you can help contribute some unit tests.
