### ISSUE TITLE
Information about FCMNotification parameters

### ISSUE THREAD

**Issue by sunil-jhamnani** [olucurious/PyFCM#74]
Hi,

I am using this module and it really seems to be very useful. Just need some information about the parameters which are passed while firing a new push notification. 

In the push_service.notify_single_device and push_service.notify_multiple_devices there are some of these parameters which I need to use but not able to find any information on what to pass in these as values:

- click_action
- tag

I am using cordova from the app side.

**Comment by olucurious** [comment]
Check here for more information: https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support
