### ISSUE TITLE
Release 1.1.0 is broken 

### ISSUE THREAD

**Issue by caiotomazelli** [olucurious/PyFCM#76]
Since release of 1.1.0, the function notify_single_device is returning None for both success and failure when sending a push notification.

Maybe writing some unit tests for verifying response format would be advisable for next release (after bug fix)?

**Comment by olucurious** [comment]
Can you help figure out what's going on? And maybe help with some unit tests

**Comment by caiotomazelli** [comment]
Yes, I'm working on it, will report soon.
