### ISSUE TITLE
ImportError: No module named 'baseapi'

### ISSUE THREAD

**Issue by peterhn** [olucurious/PyFCM#8]
I receive this error when I try to build an app with the PyFCM v0.0.4

I fixed it by changing `from baseapi import BaseAPI`

in baseapi.py to

`from .baseapi import BaseAPI`

**Comment by olucurious** [comment]
What version of python are you using? I want to see if I can replicate the issue over here

**Comment by garrett-kl** [comment]
I also have hit this.

Python 3
pyfcm==0.0.4

**Comment by olucurious** [comment]
Solved in https://github.com/olucurious/PyFCM/pull/9/

You can install the update with pip install git+git://github.com/olucurious/PyFCM.git
Thanks to MrLucasCardoso for the PR
Thanks to all for pointing this out.

Cheers
