### ISSUE TITLE
Response changed

### ISSUE THREAD

**Issue by ProsperousBloom** [olucurious/PyFCM#82]
Hi,

I was using v1.0.6 previously and the response was a single dictionary when using notify_single_device().
Now with v1.1.2 and doing exactly the same, I get a list of a dictionary. Is this intended? I couldn't find any changelogs and the examples still seem to indicate that the output should be a dictionary, rather than a list of it.

Best

**Comment by olucurious** [comment]
I'm sorry the response was changed to a list of dicts in the last update, I'm also very sorry it wasn't indicated properly in the change logs, that's entirely my fault.
