### ISSUE TITLE
hostname 'fcm.googleapis.com' doesn't match either of '*.com.com', 'com.com'

### ISSUE THREAD

**Issue by siyanew** [olucurious/PyFCM#85]
I have seen this error recently. what's the problem?
```
hostname 'fcm.googleapis.com' doesn't match either of '*.com.com', 'com.com'
```

**Comment by olucurious** [comment]
Can you pls provide more informations as to what really happened

**Comment by siyanew** [comment]
I think the problem was about the restriction in some countries that my machine was there.

**Comment by olucurious** [comment]
You can simply use the proxy feature in that case
