### ISSUE TITLE
tokens instead of api-keys

### ISSUE THREAD

**Issue by Guest007** [olucurious/PyFCM#87]
For now Firebase Cloud Messaging shows that api keys can be used, but not supported. We must use tokens for now. Is something changes in PyFCM?

**Comment by olucurious** [comment]
Can you please clarify and add references in the Firebase Cloud Messaging documentation

**Comment by Guest007** [comment]
can't find this in docs, but couple of days ago my pushes stopped to deliver. I found that my key was dropped. I made new one and got that view (on russian only) http://joxi.ru/jnAyNegcDNNqrZ
Translation of info-message:
"To send a message instead of the server keys are now used tokens Firebase Cloud Messaging. Although the server keys, you can still use them to support discontinued."

**Comment by olucurious** [comment]
I've not been able to find information abt the Firebase Cloud Messaging tokens in the http server ref, anyone here should notify us when there's any info abt the new token

**Comment by sandeshnaroju** [comment]
Yeah, Server keys are deprecated, but no problem to pyFcm, I tried it with new tokens. It is working fine. Just replace old server keys with new token.

**Comment by furkanuyar** [comment]
push_service = FCMNotification(api_key="<api-key>")
api-key should be 'Server key' at console.firebase.google.com (your project page), under CLOUD MESSAGING tab.

**Comment by shlomiLan** [comment]
Thanks, the docs are not clear, maybe it should be in the main readme page. I thought that I need to use my private key as the `api_keyz

**Comment by sanjayMantati** [comment]
Means i have to change FCM_SERVER_KEY with token??
If yes, then where i can get this token?

**Comment by shlomiLan** [comment]
@sanjayMantati  console.firebase.google.com -> Settings -> General -> Web API Key

**Comment by TheOneWayTruth** [comment]
> push_service = FCMNotification(api_key="")
> api-key should be 'Server key' at console.firebase.google.com (your project page), under CLOUD MESSAGING tab.

In what file do i define that?

**Comment by olucurious** [comment]
Wherever you're instantiating the FCMNotification class

**Comment by ray-t1** [comment]
Hello. I'm using this package to manage the server side of my in app notifications, but when i send the notification it throws an authentication error for the sender account, more explicitly:
`There was an error authenticating the sender account`.
I used the web API key provided in Firebase console but nothing changed, any clues?

**Comment by mglowinski93** [comment]
@rt-garcia 
`Cloud Messaging API (Legacy)` needs to be enabled.
After that, you will get `Server key`.

**Comment by mglowinski93** [comment]
> Hello. I'm using this package to manage the server side of my in app notifications, but when i send the notification it throws an authentication error for the sender account, more explicitly: `There was an error authenticating the sender account`. I used the web API key provided in Firebase console but nothing changed, any clues?

@rt-garcia 
`Cloud Messaging API (Legacy)` needs to be enabled.
After that, you will get `Server key`.
