### ISSUE TITLE
Delete Useless registration_id

### ISSUE THREAD

**Issue by siyanew** [olucurious/PyFCM#89]
I have an android app that sends users registration_ids to the server but when users logout or reinstall the app the registration_id changed and I save a new registration id in my database . when I want to send a notification message I send message to all registration_ids of one user. 

In sending process some responses show errors and they failed because of expired firebase registration id but how do I realize which registration id is invalid ?

```
notif_ids = notif_ids.objects.filter(user=user).all()
        for notifid in notif_ids:
            registration_id = notifid.firebase_id
            message_title = "Test"
            message_body = "Test"
            try:
                result = push_service.notify_single_device(registration_id=registration_id, message_title=message_title,
                                                           message_body=message_body, sound="Default", collapse_key="tag1")
                # How Do I understand removed and invalid registration id from result ?!
            except Exception as e:
                pass
```

**Comment by olucurious** [comment]
So, the thing is you need to map registration ids in your database with the respective users and just replace reg_ids when they change

**Comment by siyanew** [comment]
there is another issue here I don't replace users registration id with the old one because users can sign in via different devices so 1 user can have n reg_ids from different devices.

**Comment by baali** [comment]
Hey, I was looking at the [InstanceID documentation][] and first example API that is *info* can be used to identify obsolete registration ids. I can think of a function like this for BaseAPI class 

    def clean_registration_ids(self, registration_ids):
        '''Return list of active IDS from the list of registration_ids

        '''
        headers = {'Authorization':'Key:'+WEB_API_KEY,
                   'Content-Type': 'application/json; charset=UTF-8'}
        valid_registration_ids = []
        for registration_id in registration_ids:
            details = requests.get('https://iid.googleapis.com/iid/info/'+registraction_id, headers=headers, params={'details':'true'})
            if details.status_code == 200:
                valid_reg_ids.append(registration_id)
        return valid_registration_ids

Let me know what you think about this, I would be more than happy to submit a PR for the same.

[InstanceID documentation]: https://developers.google.com/instance-id/reference/server#get_information_about_app_instances

**Comment by olucurious** [comment]
@baali Thanks a lot for the contribution, I'll merge it and update pypi very soon
