### ISSUE TITLE
It takes long time to finish a request

### ISSUE THREAD

**Issue by phuong** [olucurious/PyFCM#93]
Hi there,
I'm playing with PyFCM to send message at localhost,
In my case, when I use curl, it takes <1sec to receive response.
But when y use PyFCM, it takes uncountable sec to receive response.
Any suggestion for me?

**Comment by olucurious** [comment]
Could be a network issue on your side, are you using a proxy server?

**Comment by phuong** [comment]
Yes, everything is fine when i test on other computer. Thanks.
