### ISSUE TITLE
API questions

### ISSUE THREAD

**Issue by sirdodger** [olucurious/PyFCM#95]
I am confused by the API, and it seems like the documentation does not match the behavior.

The documentation states that a single response will be returned, with counts of notifications in various states, and then an array of results in the same order as the registration ids in the request.

However, in practice, I see an both an outer array and an array in the results.  

Reading the code, it seems like the library chunks into batches of 1000, and each outer array represents a chunk of 1000, and each inner array represents each ID in that chunk.  It seems like since the library does chunking transparently to the user, that it should also transparently flatten the responses.

**Comment by sirdodger** [comment]
Actually, it seems stranger than that.  When submitting two IDs, I got back two outer elements, where the first one contained result 0, and the second one contained both results 0 and 1.

**Comment by olucurious** [comment]
The Readme file has been updated in previous updates

**Comment by sirdodger** [comment]
For example, here is a request where I sent two ids, one of which does not match the api key, and the other a totally bogus made up id.

`
[
{'failure': 1, 'canonical_ids': 0, 'success': 0, 'multicast_id': -1, 
'results': [{'error': 'MismatchSenderId'}]}, 
{'failure': 2, 'canonical_ids': 0, 'success': 0, 'multicast_id': -1, 
'results': [{'error': 'MismatchSenderId'}, {'error': 'InvalidRegistration'}]}]
`

**Comment by olucurious** [comment]
Can you also help look at the code to figure out what's going on

**Comment by olucurious** [comment]
Can I see a sample code where you calling the method? Are you calling once or twice?

**Comment by olucurious** [comment]
Basically, what happened is you called the notify methods twice and the results were accumulated, working on a fix already

**Comment by olucurious** [comment]
UPDATED and FIXED here: https://github.com/olucurious/PyFCM/releases/tag/1.2.0
