### ISSUE TITLE
1.2.0 is not updated in repo

### ISSUE THREAD

**Issue by yardensachs** [olucurious/PyFCM#96]
Hey,

Seems like the [1.2.0](https://github.com/olucurious/PyFCM/releases/tag/1.2.0) tag and the repo do not reflect PIP 1.2.0 source. e.g. `__version__` on the [only commit](https://github.com/olucurious/PyFCM/commit/a3ab995eb8b788ba17ea18b54a5db6c25089f193).

PIP 1.2.0 package is also breaking my current builds because it had changed the return values on lines 283 and 87 in `fcm.py`. I am expecting a list and I get a dict.

I guess this is not intentional.

**Comment by olucurious** [comment]
I'm so sorry, it is intentional and will soon be updated on github

**Comment by yardensachs** [comment]
at any case that's breaking the API, so it cannot stay the same major version, right?

**Comment by olucurious** [comment]
It's just a minimal change actually and fixes other underlying issues

**Comment by olucurious** [comment]
The planned changelog is:
- Updated response retrieval, notify_single_device response returns single dict while notify_multiple_devices returns a list of dicts
- You can now pass extra argument by passing it as key value in a dictionary as extra_kwargs to any notification sending method you want to use
- It is now possible to send a notification without setting body or content available

**Comment by olucurious** [comment]
UPDATED on Github here: https://github.com/olucurious/PyFCM/releases/tag/1.2.0
