### ISSUE TITLE
Empty notification key prevents browser service workers from receiving notifications

### ISSUE THREAD

**Issue by deceze** [olucurious/PyFCM#99]
Even when not setting any notification contents, trying to push only a data notification, pyfcm inserts a `"notification":{"icon":null}` stub, which appears to prevent service workers in browsers from receiving the notification.

Does not work (no notification received):

```
self.fcm.notify_multiple_devices(tokens, data_message=data, time_to_live=30)
```

Works (service worker receives notification):

```
payload = dict(
    registration_ids=tokens,
    data=data,
    time_to_live=30,
    priority='high',
)
self.fcm.send_request([json.dumps(payload)])
```

**Comment by olucurious** [comment]
Fixed here: https://github.com/olucurious/PyFCM/commit/008005ff0e74ec447939e1a8cea0fc0a513aa35a
